### ISSUE TITLE
有支持 chacha20-ietf-poly1305 算法ss节点的软件吗

### ISSUE THREAD

**Issue by yu-steven** [yu-steven/openit#153]
欢迎讨论

**Comment by git-yusteven** [comment]
我知道个魔改ss可以

**Comment by git-yusteven** [comment]
Surge也行，火箭也可以支持，wuanx也可以支持其他的呢

**Comment by izsiyy** [comment]
https://github.com/2dust/v2rayN

**Comment by wwings2016** [comment]
[订阅.txt](https://github.com/git-yusteven/openit/files/8403862/default.txt)
研究研究这个？也是用的chacha20-ietf-poly1305加密，但是导入clash可用，但是openit的转换成clash订阅却不能用

**Comment by wwings2016** [comment]
![QQ图片20220403133754](https://user-images.githubusercontent.com/102454098/161413431-d6e91d48-4a6c-4d6a-8fea-0496b1e1d586.png)

**Comment by git-yusteven** [comment]
> [订阅.txt](https://github.com/git-yusteven/openit/files/8403862/default.txt)
> 研究研究这个？也是用的chacha20-ietf-poly1305加密，但是导入clash可用，但是openit的转换成clash订阅却不能用

在新的issues里跟你说吧

https://github.com/git-yusteven/openit/issues/156#issue-1190826435
