### ISSUE TITLE
关于chacha20-ietf-poly1305加密在Clash配置文件中的实现

### ISSUE THREAD

**Issue by yu-steven** [yu-steven/openit#156]
[订阅.txt](https://github.com/git-yusteven/openit/files/8403862/default.txt)
![QQ图片20220403133754](https://user-images.githubusercontent.com/102454098/161413487-dfb75be6-7f82-46a6-871e-4438e1f01a07.png)

研究研究这个？也是用的chacha20-ietf-poly1305加密，但是导入clash可用，但是openit的转换成clash订阅却不能用

_Originally posted by @wwings2016 in https://github.com/git-yusteven/openit/issues/153#issuecomment-1086779935_

**Comment by git-yusteven** [comment]
看见了，但是同为chacha20-ietf-poly1305加密，不同的是其节点密码是长串数字

给你看一下，转换成Clash的样子
`{name: 🇭🇰 HK / DC112, server: 122.9.54.153, port: 1029, type: ss, cipher: chacha20-ietf-poly1305, password: 8d0bcb875191315e459288411c18c38963d0627e1990a8fa9cc84dd43e6e8050}`

**Comment by wwings2016** [comment]
意思是跟密码有关吗

**Comment by git-yusteven** [comment]
我猜是，我手边没有Clash，你找个Clash把上面的导入一下，正常的话，是一个90ms以内的节点

**Comment by wwings2016** [comment]
![S20403-14183227](https://user-images.githubusercontent.com/102454098/161414551-217cdec8-c4e7-419c-8065-00c02c84fe26.png)
Clash上ping不通

**Comment by git-yusteven** [comment]
🌝🌚

**Comment by izsiyy** [comment]
这种长密码俗称小火箭专属节点  我问了作者 他没有回答我

**Comment by git-yusteven** [comment]
> 这种长密码俗称小火箭专属节点 我问了作者 他没有回答我

所以先等他回复看看

**Comment by wwings2016** [comment]
我问了其他大佬，说是密码太长会截断(在Clash上)

**Comment by git-yusteven** [comment]
> 我问了其他大佬，说是密码太长会截断(在Clash上)

😢🥹😭
