### ISSUE TITLE
群bot有问题呀，刚才进群点了答案一直在loading

### ISSUE THREAD

**Issue by char1eslu** [yu-steven/openit#182]
@charles_lu，被ban了，管理大大帮忙看看吧，谢谢

**Comment by char1eslu** [comment]
好像今晚现在tg的bot都有问题，无法交互了，是与SCP频道关联的群组

**Comment by yu-steven** [comment]
联系我 [@yusteven](https://t.me/yusteven)

**Comment by yu-steven** [comment]
> 好像今晚现在tg的bot都有问题，无法交互了，是与SCP频道关联的群组

联系我 [@yusteven](https://t.me/yusteven)

**Comment by char1eslu** [comment]
> > 好像今晚现在tg的bot都有问题，无法交互了，是与SCP频道关联的群组
> 
> 联系我 [@yusteven](https://t.me/yusteven)

谢谢，已私信
