### ISSUE TITLE
请更改linkedin.com的规则

### ISSUE THREAD

**Issue by namjar** [yu-steven/openit#193]
更改为

- DOMAIN-SUFFIX,linkedin.com,🚀 节点选择

**Comment by namjar** [comment]
是的，国内IP会自动跳到 linkedin.cn，只有job

**Comment by yu-steven** [comment]
> 是的，国内IP会自动跳到 linkedin.cn，只有job

已修改，进行测试后会合并分支
可进入 yu-steven-patch-1 分支进行查看

**Comment by yu-steven** [comment]
你试一下，如果好用回应一下
https://github.com/yu-steven/openit/raw/11d3cfbbb579317bb568e1bc2d56a50d8b637e46/Clash.yaml

**Comment by namjar** [comment]
没问题了！

高效率，6个赞 👍🏻

**Comment by yu-steven** [comment]
> 没问题了！
> 
> 高效率，6个赞 👍🏻

那我合并了
