### ISSUE TITLE
B: cfw0.19.16查看节点被识别为低于0.19.10

### ISSUE THREAD

**Issue by LIPiston** [yu-steven/openit#202]
### 出现问题的订阅链接

https://openit.ml/Clash.yaml

### 你使用的是哪个应用程序？

Clash for Windows

### 复现方式

```bash
1.使用链接
2.查看 proxies
3.台湾节点


```
![image.png](https://s2.loli.net/2022/04/29/YxqwEhfuRM1CAyt.png)

**Comment by yu-steven** [comment]
请仔细阅读那段代码
必须出现为弹窗才是真正目的
现在看到的为正确输出
