### ISSUE TITLE
B: 目前是每个300小时更新一次，建议最多24小时更新一次

### ISSUE THREAD

**Issue by redstoneleo** [yu-steven/openit#203]
### 出现问题的订阅链接

https://github.com/yu-steven/openit/blob/main/Clash.yaml#L416

### 你使用的是哪个应用程序？

Clash for Windows

### 复现方式

```bash
代码里的设置
https://github.com/yu-steven/openit/blob/main/Clash.yaml#L416
目前是每个300小时更新一次，建议最多24小时更新一次。
参考文档：https://docs.neobook.co/windows/clash-for-windows-pei-zhi-jiao-cheng#she-zhi-zi-dong-geng-xin
```

**Comment by yu-steven** [comment]
首先那个300虽然我不确定它是什么，但它一定会不是更新频率。
更新频率是由Clash把你输入的订阅和更新频率等信息填入到同一个文件里（具体目录与配置文件在同一目录）
所以我不会决定订阅什么时候更新并且我这个订阅也经常不更新。
