### ISSUE TITLE
B: 安卓手机上不时连不上，尤其是晚间

### ISSUE THREAD

**Issue by redstoneleo** [yu-steven/openit#229]
### 出现问题的订阅链接

http://openit.ml/Clash.yaml

### 你使用的是哪个应用程序？

Clash for Android

### 复现方式

```bash
1.安卓手机上不时连不上，尤其是晚间
2.晚间ping测试发现全国大多数地区都是连不上（现在似乎又好了），为了能够正常使用建议将域名走cloudflare cdn
```

**Comment by yu-steven** [comment]
可以了吧现在
网址订阅服务器是自费出的
请求太多，会不稳定

**Comment by yu-steven** [comment]
套的就是cf，因为十万请求限制，后来改成了套cf防御
