### ISSUE TITLE
Q: 您好,请问这个订阅链接在qv2ray里面怎么使用?

### ISSUE THREAD

**Issue by qxqzx3489** [yu-steven/openit#232]
### 详细说明

```bash
我直接导入节点是可以的,但是订阅就不行,订阅提示找到了0个链接
```

### 这里有一些承诺需要阅读

- [ ] 我会广泛传播这个项目
- [x] 这是我深思熟虑提出的问题
- [x] 我承诺遵守社区指导方针

**Comment by yu-steven** [comment]
**首先你得给你的Qv2ray加上插件**


使用Qv2ray只要用第一个链接就好
https://opit.top/long

以我之前使用Qv2ray的记忆，Qv2ray需要在食用之前先安装ss、ssr、vmess、trojan等的插件，具体怎么做请参考Qv2ray的官方文档

https://qv2ray.net/lang/zh/plugins/

**Comment by daycat** [comment]
请提供如何复制该问题的说明，以便团队成员能够测试并如有必要，修复错误。

在你的说明中，请包括:
1. 你试图导入的具体订阅链接
2. 你的操作系统以及系统版本
3. 你所安装的Qv2ray的版本，以及 Xray/v2ray 核心的版本
4. 你的网络供应商（ISP）

并且，请尝试一下是否可以使用浏览器直接访问订阅链接

**Comment by qxqzx3489** [comment]
我试图导入的链接
https://openit.daycat.space/long
 Archlinux 5.18.11-zen1-1-zen
qv2ray 2.7 V2Ray 4.45.2
移动
浏览器可以直接访问订阅链接
感谢回复

**Comment by qxqzx3489** [comment]
感谢回复,问题目前已经解决

**Comment by daycat** [comment]
鉴于问题已经解决，我将会关闭次issue。如有其他疑问，您可以重新开启此issue。
