### ISSUE TITLE
B: 无法更新订阅。

### ISSUE THREAD

**Issue by pyyii** [yu-steven/openit#235]
### 出现问题的订阅链接

https://opit.top/long

### 你使用的是哪个应用程序？

v2rayN

### 复现方式

```bash
1.点击V2RayN软件内的更新订阅
2.信息栏提示“The request was aborted: Could not create SSL/TLS secure channel”
...
```

**Comment by wu-mx** [comment]
握手失败，尝试更新软件。

**Comment by wu-mx** [comment]
握手失败，尝试更新软件。

**Comment by pyyii** [comment]
> 握手失败，尝试更新软件。

感谢回复。目前在用5.10，试着更新到了5.29后，发现所有的订阅更新都无反应（据说有可能是新版本DNS配置有问题），5.10就只是openit提示无法建立安全通道，其他站的订阅还是能正常更新。实在没法的话，我去下一个clash for windows 或者clashN来单独使用openit吧。

**Comment by wu-mx** [comment]
openit保留了数十个备用域名，可以尝试其他方案。
https://doc.opit.top/guide/domains.html
或者使用fastgit直接从仓库订阅。

**Comment by pyyii** [comment]
> openit保留了数十个备用域名，可以尝试其他方案。 https://doc.opit.top/guide/domains.html 或者使用fastgit直接从仓库订阅。

好的，谢谢，抽空我都试试。
