### ISSUE TITLE
无法更新订阅

### ISSUE THREAD

**Issue by kurninh** [yu-steven/openit#237]
### 出现问题的订阅链接

https://suo.yt/KCu8Put

### 你使用的是哪个应用程序？

Clash for Windows

### 复现方式

```bash
1.
2.
3.
...
```

**Comment by daycat** [comment]
无法复现此issue，请重新尝试并且不要使用第三方转换。

**Comment by yu-steven** [comment]
这个订阅已经失效请使用README中的新的订阅
