### ISSUE TITLE
公用cdn无法更新，显示403

### ISSUE THREAD

**Issue by litao3113** [yu-steven/openit#238]
### 出现问题的订阅链接

https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/PublicDirectCDN.list

### 你使用的是哪个应用程序？

Quantumult X

### 复现方式

```bash
更新引用资源时
```

**Comment by yu-steven** [comment]
挂代理再更新一次
