### ISSUE TITLE
Q:check 筛选节点的条件参数怎么调？在哪个文件？

### ISSUE THREAD

**Issue by anjue39** [yu-steven/openit#245]
### 详细说明

```bash
什么: check 筛选节点的条件参数怎么调？在哪个文件？
怎么: 比如想卡延迟速度在多少以上的，在哪调？
为什么: 因为发现筛选出的很多节点不是优质的，延迟大。
```

### 这里有一些承诺需要审阅

- [x] 我会广泛传播这个项目
- [x] 这是我经过思考提出的问题
- [X] 我查阅了其他的issues，没有重复提问
- [x] 我承诺遵守社区指导方针

**Comment by yu-steven** [comment]
在 ./utils/clashcheck/config.yaml 里调
配置文件里面写备注了

**Comment by anjue39** [comment]
只是检查了timeout？我还以为有别的测速参数呢？对了有个文件合并时删除前1-34行是啥意思？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年9月23日 10:58
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] Q:check 筛选节点的条件参数怎么调？在哪个文件？ (Issue #245)





 
在 ./utils/clashcheck/config.yaml 里调
 配置文件里面写备注了

**Comment by yu-steven** [comment]
我忘记了在哪写的备注但是意思我知道
意思是删除中间环节的clash配置文件开头几段减小clash文件大小

**Comment by anjue39** [comment]
你的意思我也明白了，原来我以为比如每次120条节点左右，删除34条，留一大部分，然后补充新的34条呢。
&nbsp;对了'为什么每次都是100条左右，难道5000左右的节点每次正好筛选10s延迟的都100条左右？这个生成的条数哪里控制着呢？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年9月23日 20:53
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] Q:check 筛选节点的条件参数怎么调？在哪个文件？ (Issue #245)





 
我忘记了在哪写的备注但是意思我知道
 意思是删除中间环节的clash配置文件开头几段减小clash文件大小

**Comment by yu-steven** [comment]
> 你的意思我也明白了，原来我以为比如每次120条节点左右，删除34条，留一大部分，然后补充新的34条呢。 &nbsp;对了'为什么每次都是100条左右，难道5000左右的节点每次正好筛选10s延迟的都100条左右？这个生成的条数哪里控制着呢？ 发自我的iPhone
> […](#)

这一方面是因为筛选严格，就是在系统设计之初就考虑到了用于生产中不能有过多节点就严格筛选，另一方面之前是达到过300+的节点的，所以没有人为限制

**Comment by yu-steven** [comment]
> 你的意思我也明白了，原来我以为比如每次120条节点左右，删除34条，留一大部分，然后补充新的34条呢。 &nbsp;对了'为什么每次都是100条左右，难道5000左右的节点每次正好筛选10s延迟的都100条左右？这个生成的条数哪里控制着呢？ 发自我的iPhone
> […](#)

这一方面是因为筛选严格，就是在系统设计之初就考虑到了用于生产中不能有过多节点就严格筛选，另一方面之前是达到过300+节点的，所以没有人为限制

**Comment by anjue39** [comment]
也就是说系统对config里的采集源能扒拉的都搞了一遍，并不是只搞了一部分，也没设时间限制，比如就搞4分钟就停止爬取。几千个节点经过测连通延迟，超过3秒的，去掉一部分，去重去掉一部分，最后生成的订阅就是自然严格筛选的全部结果，多和少取决于入库节点的优良率和重复率



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月11日 16:46
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] Q:check 筛选节点的条件参数怎么调？在哪个文件？ (Issue #245)





  
你的意思我也明白了，原来我以为比如每次120条节点左右，删除34条，留一大部分，然后补充新的34条呢。 &nbsp;对了'为什么每次都是100条左右，难道5000左右的节点每次正好筛选10s延迟的都100条左右？这个生成的条数哪里控制着呢？ 发自我的iPhone
 …
  
这一方面是因为筛选严格，就是在系统设计之初就考虑到了用于生产中不能有过多节点就严格筛选，另一方面之前是达到过300+的节点的，所以没有人为限制

**Comment by yu-steven** [comment]
> 也就是说系统对config里的采集源能扒拉的都搞了一遍，并不是只搞了一部分，也没设时间限制，比如就搞4分钟就停止爬取。几千个节点经过测连通延迟，超过3秒的，去掉一部分，去重去掉一部分，最后生成的订阅就是自然严格筛选的全部结果，多和少取决于入库节点的优良率和重复率 发自我的iPhone
> […](#)

是的，没错

**Comment by yu-steven** [comment]
> 近期发现cn类的节点归属区域实际解析普遍非cn区域，不准确 发自我的iPhone
> […](#)

这是测的节点入口位置，测落地太慢了

**Comment by anjue39** [comment]
也就是说其实测的是代理服务器的位置



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月11日 20:33
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] Q:check 筛选节点的条件参数怎么调？在哪个文件？ (Issue #245)





  
近期发现cn类的节点归属区域实际解析普遍非cn区域，不准确 发自我的iPhone
 …
  
这是测的节点入口位置，测落地太慢了

**Comment by yu-steven** [comment]
> 本地搭建nginx服务器，只需用到clashcheck和pool文件夹，运行./clashcheck/main.py，最后生成check.yaml文件。然后在github action里通过一个secret 调用本地的check.yaml作为中间量？ 发自我的iPhone
> […](#)

是，但是只要clashcheck文件夹就够了

**Comment by anjue39** [comment]
嗯，前面其实你已回复过我。不过，我不太熟悉搭建Python环境，nginx服务器啥的，我正在查资料学习，不过基本上确定尽量用docker去搭建，只用clashcheck，把池子扔进它目录即可。你推荐的那个内网穿透也着实方便。要是有个明确的简单的搭建教程就好了，我不太擅长python相关。
我去close #249，太长了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月12日 04:25
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] Q:check 筛选节点的条件参数怎么调？在哪个文件？ (Issue #245)





  
本地搭建nginx服务器，只需用到clashcheck和pool文件夹，运行./clashcheck/main.py，最后生成check.yaml文件。然后在github action里通过一个secret 调用本地的check.yaml作为中间量？ 发自我的iPhone
 …
  
是，但是只要clashcheck文件夹就够了

**Comment by yu-steven** [comment]
> 嗯，前面其实你已回复过我。不过，我不太熟悉搭建Python环境，nginx服务器啥的，我正在查资料学习，不过基本上确定尽量用docker去搭建，只用clashcheck，把池子扔进它目录即可。你推荐的那个内网穿透也着实方便。要是有个明确的简单的搭建教程就好了，我不太擅长python相关。 我去close #249，太长了。 发自我的iPhone
> […](#)

好的

**Comment by yu-steven** [comment]
我推荐那个内网穿透 [cpolar](https://www.cpolar.com) 确实方便，我玩过几次，但是没用用在生产环境里。
开启cpolar后可以在后台（127.0.0.1:端口)查看网站访问的各种信息的日志面板，比如302、404、200这样的都可以实时查看

**Comment by yu-steven** [comment]
我推荐那个内网穿透 [cpolar](https://www.cpolar.com) 确实方便，我玩过几次，但是没用用在生产环境里。
开启cpolar后可以在后台（127.0.0.1:端口)查看网站访问的各种信息的日志面板，比如302、404、200这样的都可以实时查看，非常直观

**Comment by yu-steven** [comment]
> > 嗯，前面其实你已回复过我。不过，我不太熟悉搭建Python环境，nginx服务器啥的，我正在查资料学习，不过基本上确定尽量用docker去搭建，只用clashcheck，把池子扔进它目录即可。你推荐的那个内网穿透也着实方便。要是有个明确的简单的搭建教程就好了，我不太擅长python相关。 我去close #249，太长了。 发自我的iPhone
> > […](#)
> 
> 好的

docker如果python环境不好搭你可以直接拉取python的镜像就不用拉取系统基础镜像搭了

**Comment by yu-steven** [comment]
> 嗯，前面其实你已回复过我。不过，我不太熟悉搭建Python环境，nginx服务器啥的，我正在查资料学习，不过基本上确定尽量用docker去搭建，只用clashcheck，把池子扔进它目录即可。你推荐的那个内网穿透也着实方便。要是有个明确的简单的搭建教程就好了，我不太擅长python相关。 我去close #249，太长了。 发自我的iPhone
> […](#)

docker如果python环境不好搭你可以直接拉取python的镜像就不用拉取系统基础镜像搭了

`FORM python:latest`

**Comment by yu-steven** [comment]
> 嗯，前面其实你已回复过我。不过，我不太熟悉搭建Python环境，nginx服务器啥的，我正在查资料学习，不过基本上确定尽量用docker去搭建，只用clashcheck，把池子扔进它目录即可。你推荐的那个内网穿透也着实方便。要是有个明确的简单的搭建教程就好了，我不太擅长python相关。 我去close #249，太长了。 发自我的iPhone
> […](#)

docker如果python环境不好搭你可以直接拉取python的镜像就不用拉取系统基础镜像搭了

`FROM python:latest`

**Comment by yu-steven** [comment]
> 嗯，前面其实你已回复过我。不过，我不太熟悉搭建Python环境，nginx服务器啥的，我正在查资料学习，不过基本上确定尽量用docker去搭建，只用clashcheck，把池子扔进它目录即可。你推荐的那个内网穿透也着实方便。要是有个明确的简单的搭建教程就好了，我不太擅长python相关。 我去close #249，太长了。 发自我的iPhone
> […](#)

docker如果python环境不好搭你可以直接拉取python的镜像就不用拉取系统基础镜像搭了

`FROM python:3`

**Comment by anjue39** [comment]
![image](https://user-images.githubusercontent.com/98279987/195263174-840fbfa7-e469-44dd-88e3-a405ee065312.png)
为什么不良林本地网络测速这么好的节点，实测放入pcrs系统入不了选？影响因素是?

**Comment by yu-steven** [comment]
如果上述条件没错的话，那主要是测试方法的不同

**Comment by yu-steven** [comment]
> 把它放在了poo里参与筛选，用的github的服务器上的，不是国内的。差别这么大吗？你本地测出的节点池，最后生成的每批订阅，能使用的占多少比例。现在你的订阅里我能使用的大概50个节点有四五个的比例 发自我的iPhone
> […](#)

所以你的clashcheck在GitHub的服务器？那是一定不可能入选的

**Comment by anjue39** [comment]
本地服务我不会弄😅😅大体框架我知道，Python我不太熟



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月12日 18:38
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] Q:check 筛选节点的条件参数怎么调？在哪个文件？ (Issue #245)





 
如果上述条件没错的话，那主要是测试方法的不同

**Comment by yu-steven** [comment]
> 本地服务我不会弄😅😅大体框架我知道，Python我不太熟 发自我的iPhone
> […](#)

如果GitHub的服务器可以测出来我也不会费劲弄个国内服务器了，国内服务器是必须的，而且必须是家宽线路，GFW对商宽限制级别低

**Comment by anjue39** [comment]
你以前没做调用本地的，最近才上的。9.15日左右



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月12日 18:46
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] Q:check 筛选节点的条件参数怎么调？在哪个文件？ (Issue #245)





  
本地服务我不会弄😅😅大体框架我知道，Python我不太熟 发自我的iPhone
 …
  
如果GitHub的服务器可以测出来我也不会费劲弄个国内服务器了，国内服务器是必须的，而且必须是家宽线路，GFW对商宽限制级别低

**Comment by yu-steven** [comment]
> 是的，在git服务器，就像你以前的那样。你用的哪个梯子？我更多指路由器里的梯子。所以我觉得在不在本地clashcheck筛选，没什么意义 发自我的iPhone
> […](#)

没意义就没意义呗，循序渐进，慢慢来

**Comment by yu-steven** [comment]
使用国内服务器是openit递归进化的结果

**Comment by anjue39** [comment]
是的，可以用，100个里有七八个至少可以。够用，但是一眼看不出哪个能用，时间浪费在这上面。而免费节点的生命周期平均才一两天。我一般都是把订阅出来的几十个扔到openclash里，直接用pcrs系统自带的策略就很好。openclash能自动找出最快的。但也有各种问题，比如测延迟经常不自动，切换节点就会短时中断网络，订阅节点或代理集不能自动更新的问题们



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月12日 18:50
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] Q:check 筛选节点的条件参数怎么调？在哪个文件？ (Issue #245)





  
你以前没做调用本地的，最近才上的。9.15日左右 发自我的iPhone
 …
  
没调用本地调用GitHub是临时方案，因为clashcheck可以在国外环境下筛选出来差不多的节点，可以用，但是不准确

**Comment by anjue39** [comment]
打错字了，我是说：不在本地服务器筛选，没意义。就像你说的，能用，不精准



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月12日 18:52
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] Q:check 筛选节点的条件参数怎么调？在哪个文件？ (Issue #245)





  
是的，在git服务器，就像你以前的那样。你用的哪个梯子？我更多指路由器里的梯子。所以我觉得在不在本地clashcheck筛选，没什么意义 发自我的iPhone
 …
  
没意义就没意义呗，循序渐进，慢慢来

**Comment by yu-steven** [comment]
> 是的，可以用，100个里有七八个至少可以。够用，但是一眼看不出哪个能用，时间浪费在这上面。而免费节点的生命周期平均才一两天。我一般都是把订阅出来的几十个扔到openclash里，直接用pcrs系统自带的策略就很好。openclash能自动找出最快的。但也有各种问题，比如测延迟经常不自动，切换节点就会短时中断网络，订阅节点或代理集不能自动更新的问题们 发自我的iPhone
> […](#)

嗯

**Comment by yu-steven** [comment]
> 打错字了，我是说：不在本地服务器筛选，没意义。就像你说的，能用，不精准 发自我的iPhone
> […](#)

个人筛选可以，但是像我这种公开的订阅，只是GitHub的服务器的准确度是不够的

**Comment by anjue39** [comment]
跟dns关系大吗？我一个朋友总说用smartdns能解决这些问题，它说原则上是节点大多能用，只要smartdns设置足够多的dns就好



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月12日 18:52
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] Q:check 筛选节点的条件参数怎么调？在哪个文件？ (Issue #245)





 
使用国内服务器是openit递归进化的结果

**Comment by yu-steven** [comment]
> 跟dns关系大吗？我一个朋友总说用smartdns能解决这些问题，它说原则上是节点大多能用，只要smartdns设置足够多的dns就好 发自我的iPhone
> […](#)

我写的clash dns策略就是写了一堆备用DNS
啥DoT DoH 都写了一堆

**Comment by anjue39** [comment]
我是比较排斥smartdns，也可能是没设置对，用了它比如不用梯子gitgub都能打开，200多毫秒，用了它，就2000多毫秒了，说不定归属到哪去了。因为不用梯子，光靠运营商的dns至少国内都能畅快打开。用了smartdns，国内的也很多慢了，前面计算需要5秒，后面突然打开，它总时并没像别人说的快了


路由器里的酸酸乳你推荐用哪个比较好



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月12日 19:01
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] Q:check 筛选节点的条件参数怎么调？在哪个文件？ (Issue #245)





  
跟dns关系大吗？我一个朋友总说用smartdns能解决这些问题，它说原则上是节点大多能用，只要smartdns设置足够多的dns就好 发自我的iPhone
 …
  
我写的clash dns策略就是写了一堆备用DNS
 啥DoT DoH 都写了一堆

**Comment by yu-steven** [comment]
> 我是比较排斥smartdns，也可能是没设置对，用了它比如不用梯子gitgub都能打开，200多毫秒，用了它，就2000多毫秒了，说不定归属到哪去了。因为不用梯子，光靠运营商的dns至少国内都能畅快打开。用了smartdns，国内的也很多慢了，前面计算需要5秒，后面突然打开，它总时并没像别人说的快了 路由器里的酸酸乳你推荐用哪个比较好 发自我的iPhone
> […](#)

smartDNS 在某些软件上会并发DNS请求到各种备用DNS，取最快的DNS应答，而大多数是国内的114.114.114.114等的有着物理距离上的优势，在你不开代理的时候这种优势顺便在没有节点拖慢速度后变得更大，然鹅速度快这不代表一定正确，最后，根治的方法就是修改本地的host文件把常用的网站诸如Google、GitHub的直接绑定到其域名，这样的话浏览器会先查看本地host文件查找到，这样就会立刻访问其域名的ip以达到最快响应速度

**Comment by yu-steven** [comment]
但是关于路由器上的软件没用过

**Comment by yu-steven** [comment]
> 是的，你没发现吗，大多梯子软件里的延迟是不准确的，它不代表能用，只有以本地到谷歌或者y2b这样的连通延迟才能代表能用不能用，好用不好用。我有个奇怪的现象，不良林里直播推流里的节点我大多能用，而用它不良林测速软件测出来的，大多不能用，即便参数很好，我都怀疑它软件里的测速地址不是外网谷歌y2b之类的 发自我的iPhone
> […](#)

不是测试地址的不对，是模拟真实上网环境的不完全，即只是测试了tcp没有测试真延迟以及速度，就会出现我们常说的“假节点”

**Comment by yu-steven** [comment]
> 非常有道理！！！我现在是路由器里openclash+bypass（内置smartdns+china ng），openclash yacd面板里的测延迟很准，我觉得它是真正的本地到目标url，基本上能有数据的都能用，所以每批订阅，我先进openclash，测延迟看哪个能用，暗暗记下，关掉（因为我的openclash一直不能自动更新订阅，需删掉配置重新订阅才行，所以我一直耿耿于怀，嫌麻烦）接下来导入bypass，它的机制我认可，它先用chinadns-ng大概识别国内外，再用轻量级smartdns去分配，基本上只要能用的节点很少有问题，而这些又无需设置，且能自动更新订阅，连url格式都能导入，clash格式不支持导入订阅 发自我的iPhone
> […](#)

👍

**Comment by anjue39** [comment]
？你的是真测的延迟？所谓的真延迟测速是指？测延迟我一直以为就是tcp延迟，很多软件上也是写着tcp延迟测速呀。
不良林里可测延迟，也可以测下载速度，但是玄学的是，下载速度10m/s的我这都不一定能用，至少谷歌还是打不开
另外你几次提到模拟真实上网环境，你这里指的就是本地环境为参照物连通情况？

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月12日 19:20
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] Q:check 筛选节点的条件参数怎么调？在哪个文件？ (Issue #245)





  
是的，你没发现吗，大多梯子软件里的延迟是不准确的，它不代表能用，只有以本地到谷歌或者y2b这样的连通延迟才能代表能用不能用，好用不好用。我有个奇怪的现象，不良林里直播推流里的节点我大多能用，而用它不良林测速软件测出来的，大多不能用，即便参数很好，我都怀疑它软件里的测速地址不是外网谷歌y2b之类的 发自我的iPhone
 …
  
不是测试地址的不对，是模拟真实上网环境的不完全，即只是测试了tcp没有测试真延迟以及速度，就会出现我们常说的“假节点”

**Comment by yu-steven** [comment]
> ？你的是真测的延迟？所谓的真延迟测速是指？测延迟我一直以为就是tcp延迟，很多软件上也是写着tcp延迟测速呀。 不良林里可测延迟，也可以测下载速度，但是玄学的是，下载速度10m/s的我这都不一定能用，至少谷歌还是打不开 另外你几次提到模拟真实上网环境，你这里指的就是本地环境为参照物连通情况？ 发自我的iPhone
> […](#)

真延迟作为广泛存在的名次出现在Windows版的v2ray工具里，他的意思是使用https测量节点延迟，这最接近真实环境，因为我们上网就是用的https访问网站

**Comment by yu-steven** [comment]
> 另外你几次提到模拟真实上网环境，你这里指的就是本地环境为参照物连通情况？ 发自我的iPhone
> […](#)

是的

**Comment by anjue39** [comment]
pcrs系统测的是tcp还是https延迟？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月12日 19:50
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] Q:check 筛选节点的条件参数怎么调？在哪个文件？ (Issue #245)





  
？你的是真测的延迟？所谓的真延迟测速是指？测延迟我一直以为就是tcp延迟，很多软件上也是写着tcp延迟测速呀。 不良林里可测延迟，也可以测下载速度，但是玄学的是，下载速度10m/s的我这都不一定能用，至少谷歌还是打不开 另外你几次提到模拟真实上网环境，你这里指的就是本地环境为参照物连通情况？ 发自我的iPhone
 …
  
真延迟作为广泛存在的名次出现在Windows版的v2ray工具里，他的意思是使用https测量节点延迟，这最接近真实环境，因为我们上网就是用的https访问网站

**Comment by anjue39** [comment]
这不禁让我想到你wiki里说的那个dns防污染推荐的那个clash软件里的“Xin”的勾选，那个自定义配置文件大概也有点这个意思



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月12日 19:18
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] Q:check 筛选节点的条件参数怎么调？在哪个文件？ (Issue #245)





  
我是比较排斥smartdns，也可能是没设置对，用了它比如不用梯子gitgub都能打开，200多毫秒，用了它，就2000多毫秒了，说不定归属到哪去了。因为不用梯子，光靠运营商的dns至少国内都能畅快打开。用了smartdns，国内的也很多慢了，前面计算需要5秒，后面突然打开，它总时并没像别人说的快了 路由器里的酸酸乳你推荐用哪个比较好 发自我的iPhone
 …
  
smartDNS 在某些软件上会并发DNS请求到各种备用DNS，取最快的DNS应答，而大多数是国内的114.114.114.114等的有着物理距离上的优势，在你不开代理的时候这种优势顺便在没有节点拖慢速度后变得更大，然鹅速度快这不代表一定正确，最后，根治的方法就是修改本地的host文件把常用的网站诸如Google、GitHub的直接绑定到其域名，这样的话浏览器会先查看本地host文件查找到，这样就会立刻访问其域名的ip以达到最快响应速度

**Comment by yu-steven** [comment]
> pcrs系统测的是tcp还是https延迟？ 发自我的iPhone
> […](#)

是https

**Comment by yu-steven** [comment]
> 这不禁让我想到你wiki里说的那个dns防污染推荐的那个clash软件里的“Xin”的勾选，那个自定义配置文件大概也有点这个意思 发自我的iPhone
> […](#)

哪个wiki 我咋不知道

**Comment by anjue39** [comment]
提个小建议：虽然参考意义不大，因为实际非本地环境不同，但延迟数据可否有显示或者订阅出来的可以按延迟排序或者有个标记，这样也好一眼有个轻重。类似不良林里命名



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月12日 19:58
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] Q:check 筛选节点的条件参数怎么调？在哪个文件？ (Issue #245)





  
pcrs系统测的是tcp还是https延迟？ 发自我的iPhone
 …
  
是https

**Comment by yu-steven** [comment]
> 提个小建议：虽然参考意义不大，因为实际非本地环境不同，但延迟数据可否有显示或者订阅出来的可以按延迟排序或者有个标记，这样也好一眼有个轻重。类似不良林里命名 发自我的iPhone
> […](#)

确实是个好主意，我先记下了

**Comment by anjue39** [comment]
Base64 https://openit.daycat.space/long
小火箭 https://openit.daycat.space/https
Clash https://openit.daycat.space/clash
Quanx https://openit.daycat.space/qx

你这几个是同步的，没用到cdn？国内的服务器的链接？
我现在用的时差能差一天，如下图
![image](https://user-images.githubusercontent.com/98279987/195352748-7cfa8178-4183-4185-b7fd-a69f64264055.png)

顺便说一下，你fork的TopFreeProxies近几日连续生成错误了，同步源即可，虽然你没有用到

**Comment by yu-steven** [comment]
我趣，我才发现我还在运行fork来的TopFreeProxies

**Comment by yu-steven** [comment]
不行，我要删库，删Fork的TopFreeProxies

**Comment by anjue39** [comment]
我昨天就删了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月12日 21:21
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] Q:check 筛选节点的条件参数怎么调？在哪个文件？ (Issue #245)





 
不行，我要删库，删Fork的TopFreeProxies

**Comment by yu-steven** [comment]
> 我也后来发现的，运行6小时出错，停都停不了，一看是fork你的 发自我的iPhone
> […](#)

我趣，五个月了，我才看到啊啊啊

**Comment by yu-steven** [comment]
> 同步作者的就没事了，或者cancel掉workfow不运行就可以 发自我的iPhone
> […](#)

好了，删库了，真的浪费资源
