### ISSUE TITLE
现在生成的订阅节点只有40来条，且都不能用了

### ISSUE THREAD

**Issue by anjue39** [yu-steven/openit#247]
### 出现问题的订阅链接

https://openit.daycat.space/clash

### 复现方式

```bash
现在生成的订阅节点只有40来条，且都不能用了。这两天调整代码后，出现很多问题
```

**Comment by yu-steven** [comment]
没办法，现在没几个节点

**Comment by wonjar** [comment]
@yu-steven 最近墙对tls发力，可以考虑一部分节点从vmess和trojan换成ss aead

**Comment by yu-steven** [comment]
您说的对，但是节点不是我的，这都是我搜集的

> @yu-steven 最近墙对tls发力，可以考虑一部分节点从vmess和trojan换成ss aead

**Comment by anjue39** [comment]
> 没办法，现在没几个节点

pool-config.yml中前些日子新增了好多个节点，我试了几个都能用呀。现在好像又删了
最近ss ssr节点几乎生成的没有，是咋回事？

**Comment by anjue39** [comment]
> 没办法，现在没几个节点
# d8517b2d7a658180647b4f42cdb1854498223930
两天前删除了大量节点，这些不能用了？

**Comment by anjue39** [comment]
> 没办法，现在没几个节点

我很纳闷，按说，光pub/main/data/里的这些base 节点都用不过来呀，再加上config.yml里免费的机场，怎么最后生产出来的只有那几个，base节点参与进去了吗

**Comment by yu-steven** [comment]
> > 没办法，现在没几个节点
> 
> # [d8517b2](https://github.com/yu-steven/openit/commit/d8517b2d7a658180647b4f42cdb1854498223930)
> 两天前删除了大量节点，这些不能用了？

因为搜集只接受clash格式所以造成很多url格式的节点不识别也就搜集不上，因此我都给删了

**Comment by anjue39** [comment]
大佬，请教一下，base url里pub那些节点，被收集了吗？main.py里看代码也没看到生成到out.yaml里呀。现在代码里有三个源，pool/config.yaml，pub里的base url，还有sub里的source.yaml，到底程序爬取的是哪个？freev2里的main.py就几行，它怎么爬的免费机场生成的订阅



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月8日 10:32
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 现在生成的订阅节点只有40来条，且都不能用了 (Issue #247)





   
没办法，现在没几个节点
  
d8517b2
 
两天前删除了大量节点，这些不能用了？
  
因为搜集只接受clash格式所以造成很多url格式的节点不识别也就搜集不上，因此我都给删了

**Comment by yu-steven** [comment]
我先回答我看懂的部分: 进入utils/pool/，python运行 main.py python引用 config.yaml 生成文件output.yaml｜sub/ 和 utils/freev2文件夹不参与搜集和筛选系统
再说我看不懂的部分: “base url”是什么 “pub”是什么 out.yaml在哪看见的 “pub里的base url”是什么
**请先在问我的时候里添加全局环境变量我才能看懂**

**Comment by anjue39** [comment]
> 我先回答我看懂的部分: 进入utils/pool/，python运行 main.py python引用 config.yaml 生成文件output.yaml sub/ 和 utils/freev2文件夹不参与搜集和筛选系统 再说我看不懂的部分: “base url”是什么 “pub”是什么 out.yaml在哪看见的 “pub里的base url”是什么 **问我的时候请先引入上下文我才能看懂**

刚才说的out.yaml文件名有误，我说的是output.yaml，pub里的data我说的是
![image](https://user-images.githubusercontent.com/98279987/194693607-b8c27ed8-4470-452a-862e-63ee8b031482.png)
我特别想知道sub/source.yaml里的订阅节点参与搜集了吗，这个文件里的订阅是做啥用的
![image](https://user-images.githubusercontent.com/98279987/194693780-5840e021-dbe9-4169-a9c7-6817a233e9ff.png)

**Comment by yu-steven** [comment]
图一搜集，图二我刚刚说过了不参与搜集😅

**Comment by anjue39** [comment]
> 图一搜集，图二我刚刚说过了不参与搜集😅 图二里的干啥用？是另外一个系统的配置文件 output.yaml难道没有生成吗？

收到👌🏻，再追问一下，比如生成的节点里我通过进一步测速什么的，确定了5个节点，我想单独订阅这5个节点，要么我手动弄个input.yaml文件放在clashcheck/ 进行筛选或到clashcheck 中 config.yaml 里的 更改source: 项以引用并筛选网络中的clash配置文件？

ulr格式不能爬取的问题，如果把它转为clash格式，先不管什么规则，订阅转换一下，再走程序爬取，可行吗？比如https://raw.githubusercontent.com/changfengoss/pub/main/data/这里面的，先扒拉过来，不管里面什么格式，先统一转换成clash格式，再最终入库，进入筛选机制

**Comment by yu-steven** [comment]
可以

**Comment by anjue39** [comment]
> 可以

有无快速输入自定义节点，用大佬程序里有效相关模块生成订阅的方式？放入到clashcheck的input.yaml还要筛选，没必要，已经筛选过了。另自定义节点必须采用clash标准格式吗？有点啰嗦，简单一句话，几十个节点中经过去重再测速啥的，有效的就几个，我找出来后，扔进程序那个环节，不用筛选，直接按照程序自带rule，生成一个有效的订阅

**Comment by yu-steven** [comment]
猜你喜欢: 订阅转换 https://sub.tsutsu.one/

> > 可以
> 
> 有无快速输入自定义节点，用大佬程序里有效相关模块生成订阅的方式？放入到clashcheck的input.yaml还要筛选，没必要，已经筛选过了。另自定义节点必须采用clash标准格式吗？有点啰嗦，简单一句话，几十个节点中经过去重再测速啥的，有效的就几个，我找出来后，扔进程序那个环节，不用筛选，直接按照程序自带rule，生成一个有效的订阅

**Comment by anjue39** [comment]
> 猜你喜欢: 订阅转换 https://sub.tsutsu.one/
不好玩，我还是在本代码里做个input-diy.yaml或者check-diy.yaml吧，把要自定义输入的直接扔进去，跳过筛选环节，直接对接rm去重排序，经由converter，再做个nodes-diy.yaml，去掉不需要的环节，不需要删除原输入文件，直接生成最后的订阅Clash-diy.yaml和其它格式吧，感觉内置的rule还不错

**Comment by anjue39** [comment]
> 猜你喜欢: 订阅转换 https://sub.tsutsu.one/

不好玩，我还是在本代码里做个input-diy.yaml或者check-diy.yaml吧，把要自定义输入的直接扔进去，跳过筛选环节，直接对接rm去重排序，经由converter，再做个nodes-diy.yaml，去掉不需要的环节，不需要删除原输入文件，直接生成最后的订阅Clash-diy.yaml和其它格式吧，感觉内置的rule还不错

**Comment by yu-steven** [comment]
好吧，可以close了吗

**Comment by anjue39** [comment]
可以了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月9日 20:07
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 现在生成的订阅节点只有40来条，且都不能用了 (Issue #247)





 
好吧，可以close了吗

**Comment by anjue39** [comment]
不过，感觉你是活生生把url里的ss/ssr节点合并过去了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月9日 20:07
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 现在生成的订阅节点只有40来条，且都不能用了 (Issue #247)





 
好吧，可以close了吗

**Comment by yu-steven** [comment]
部分手动加入的节点是暂时的高优先级的
