### ISSUE TITLE
F: 去重希望再加强些，有些节点其实是一个

### ISSUE THREAD

**Issue by anjue39** [yu-steven/openit#248]
### 详细说明

```bash
trojan://6c4e3611-5f2d-4eb5-8c56-3e2b850e4cca@165.154.253.15:49006?allowInsecure=1#🇨🇦CA 5 → openitsub.com
trojan://6c4e3611-5f2d-4eb5-8c56-3e2b850e4cca@165.154.253.15:49007?allowInsecure=1#🇨🇦CA 3 → openitsub.com
trojan://6c4e3611-5f2d-4eb5-8c56-3e2b850e4cca@165.154.253.15:49008?allowInsecure=1#🇨🇦CA 1 → openitsub.com

类似这样的节点，有时候生成的连续一堆相似的，其实几乎是同一个节点，能不能去重，只是端口不同而已
```

**Comment by yu-steven** [comment]
扫端口的，这种被认为是三个节点，虽然本身确实是同一个节点

**Comment by anjue39** [comment]
建议根据特征字符串优化去重一下，其实几十个节点里就几个能用，要么是重复，要么是无效服务器



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月8日 10:30
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] F: 去重希望再加强些，有些节点其实是一个 (Issue #248)





 
扫端口的，这种被认为是三个节点，虽然本身确实是同一个节点

**Comment by yu-steven** [comment]
OK

**Comment by anjue39** [comment]
可以像不良林命名那样节点名称加入速度吗？目前的速度只因只是延迟测速？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: WuMX ***@***.***&gt;
发送时间: 2022年10月9日 22:58
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] F: 去重希望再加强些，有些节点其实是一个 (Issue #248)





 
这种国内机一机多端口的很大程度上是不同节点（一个入口不同落地），去重的最终形式其实应该是按照 落地去看。目前该项目用的是最原始的去重方式，详情可以去看pcrs r部分源代码。

**Comment by yu-steven** [comment]
> 可以像不良林命名那样节点名称加入速度吗？目前的速度只因只是延迟测速？ 发自我的iPhone
> […](#)

加入速度会占用很多时间，然鹅这也并没有用
