### ISSUE TITLE
几个问题咨询请教

### ISSUE THREAD

**Issue by anjue39** [yu-steven/openit#251]
Base64 https://openit.daycat.space/long
小火箭 https://openit.daycat.space/https
Clash https://openit.daycat.space/clash
Quanx https://openit.daycat.space/qx

你这几个是同步的，没用到cdn？国内的服务器的链接？
我现在用的时差能差一天，如下图
![image](https://user-images.githubusercontent.com/98279987/195352748-7cfa8178-4183-4185-b7fd-a69f64264055.png)

---
我测试了你生产的节点，虽然也是国内机器产出的，但是也是很多用不了在我本地，我以为会乐观一点。从优良率和兼容性来综合来看，看来中间有个国内的有代表的中间商服务器做clashcheck可能才是中庸的

### 这里有一些承诺需要审阅

- [ ] 我会广泛传播这个项目
- [X] 这是我经过思考提出的问题
- [X] 我查阅了其他的issues，没有重复提问
- [X] 我承诺遵守社区指导方针

**Comment by anjue39** [comment]
默认用的是哪个rule，如果在线转换选择哪个跟系统的是一致的？神马规则？

**Comment by yu-steven** [comment]
> 默认用的是哪个rule，如果在线转换选择哪个跟系统的是一致的？神马规则？

你不会去看README吗，声明那一栏写的很清楚啊

**Comment by yu-steven** [comment]
> Base64 https://openit.daycat.space/long 小火箭 https://openit.daycat.space/https Clash https://openit.daycat.space/clash Quanx https://openit.daycat.space/qx
> 
> 你这几个是同步的，没用到cdn？国内的服务器的链接？ 我现在用的时差能差一天，如下图 ![image](https://user-images.githubusercontent.com/98279987/195352748-7cfa8178-4183-4185-b7fd-a69f64264055.png)
> 
> 我测试了你生产的节点，虽然也是国内机器产出的，但是也是很多用不了在我本地，我以为会乐观一点。从优良率和兼容性来综合来看，看来中间有个国内的有代表的中间商服务器做clashcheck可能才是中庸的
> 
> ### 这里有一些承诺需要审阅
> * [ ]  我会广泛传播这个项目
> * [x]  这是我经过思考提出的问题
> * [x]  我查阅了其他的issues，没有重复提问
> * [x]  我承诺遵守社区指导方针

没看懂你说的啥，每一次的访问都是同步的

**Comment by anjue39** [comment]
没经过cdn就是同步。这些天我一直脑短路，按说找个国内的一个空间放个订阅应该不是难事，我曾想过用网盘搞出直链。总觉得有更简单的方式



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月13日 09:34
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 几个问题咨询请教 (Issue #251)





  
Base64 https://openit.daycat.space/long 小火箭 https://openit.daycat.space/https Clash https://openit.daycat.space/clash Quanx https://openit.daycat.space/qx
 
你这几个是同步的，没用到cdn？国内的服务器的链接？ 我现在用的时差能差一天，如下图 
 
我测试了你生产的节点，虽然也是国内机器产出的，但是也是很多用不了在我本地，我以为会乐观一点。从优良率和兼容性来综合来看，看来中间有个国内的有代表的中间商服务器做clashcheck可能才是中庸的
 
这里有一些承诺需要审阅
  
  我会广泛传播这个项目 

  这是我经过思考提出的问题 

  我查阅了其他的issues，没有重复提问 

  我承诺遵守社区指导方针 
  
没看懂你说的啥，每一次的访问都是同步的

**Comment by anjue39** [comment]
我在说cdn最近不正常，差3个小时。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月13日 09:34
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 几个问题咨询请教 (Issue #251)





  
Base64 https://openit.daycat.space/long 小火箭 https://openit.daycat.space/https Clash https://openit.daycat.space/clash Quanx https://openit.daycat.space/qx
 
你这几个是同步的，没用到cdn？国内的服务器的链接？ 我现在用的时差能差一天，如下图 
 
我测试了你生产的节点，虽然也是国内机器产出的，但是也是很多用不了在我本地，我以为会乐观一点。从优良率和兼容性来综合来看，看来中间有个国内的有代表的中间商服务器做clashcheck可能才是中庸的
 
这里有一些承诺需要审阅
  
  我会广泛传播这个项目 

  这是我经过思考提出的问题 

  我查阅了其他的issues，没有重复提问 

  我承诺遵守社区指导方针 
  
没看懂你说的啥，每一次的访问都是同步的

**Comment by anjue39** [comment]
我知道你的规则内容，我是问是和网上官方某个规则是一致的？还是你自己弄的？还有策略部分，是你弄的还是网上的，也就是说1-196行包括规则和策略，这196行是网上某个规则吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月13日 09:33
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 几个问题咨询请教 (Issue #251)





  
默认用的是哪个rule，如果在线转换选择哪个跟系统的是一致的？神马规则？
  
你不会去看README吗，声明那一栏写的很清楚啊

**Comment by yu-steven** [comment]
> 我知道你的规则内容，我是问是和网上官方某个规则是一致的？还是你自己弄的？还有策略部分，是你弄的还是网上的，也就是说1-196行包括规则和策略，这196行是网上某个规则吗 发自我的iPhone
> […](#)

都是我自己写的配合subconverter使用

**Comment by yu-steven** [comment]
> 没经过cdn就是同步。这些天我一直脑短路，按说找个国内的一个空间放个订阅应该不是难事，我曾想过用网盘搞出直链。总觉得有更简单的方式 发自我的iPhone
> […](#)

**Comment by yu-steven** [comment]
抱歉，点错了

**Comment by anjue39** [comment]
我问这个，主要是你的rule在openclash订阅加载后，策略组和节点两部分，如果清空节点，保存应用，就会出现一个提示："Parse config error: proxy group[0]: `use` or `proxies` missing"。所以我想问你如果是网上某个规则，我去对一下，看是不是哪标点符号有问题。因为别的规则官方的，没发现过有些问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月13日 09:33
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 几个问题咨询请教 (Issue #251)





  
默认用的是哪个rule，如果在线转换选择哪个跟系统的是一致的？神马规则？
  
你不会去看README吗，声明那一栏写的很清楚啊

**Comment by anjue39** [comment]
没关系，太长了我就会自关。我问你的问题都快成wiki库了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月13日 09:53
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 几个问题咨询请教 (Issue #251)





 
抱歉，点错了

**Comment by yu-steven** [comment]
> 我问这个，主要是你的rule在openclash订阅加载后，策略组和节点两部分，如果清空节点，保存应用，就会出现一个提示："Parse config error: proxy group[0]: `use` or `proxies` missing"。所以我想问你如果是网上某个规则，我去对一下，看是不是哪标点符号有问题。因为别的规则官方的，没发现过有些问题 发自我的iPhone
> […](#)

为什么要清空节点？清空之后当然就是proxies missing了

**Comment by yu-steven** [comment]
虽然不知道官方的规则可以不报错，但是我这个规则正常用不会出错

**Comment by anjue39** [comment]
说起来无奈，openclash有个代理集的设置，这种方法跟直接添加订阅的不同就是，它可以每次不用更新策略，只更新服务节点，而且可以设置间隔时长和测速。但前提是要么用它内置的规则+代理集，要么就先添加策略组，然后再加入代理集，代理集的格式其实就是pool.yaml那种去了196行的list条目。所以我清空了节点，保留了策略组，加入了代理集，然后保存应用。结果就出那个提示最终启动不了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月13日 09:57
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 几个问题咨询请教 (Issue #251)





  
我问这个，主要是你的rule在openclash订阅加载后，策略组和节点两部分，如果清空节点，保存应用，就会出现一个提示："Parse config error: proxy group[0]: use or proxies missing"。所以我想问你如果是网上某个规则，我去对一下，看是不是哪标点符号有问题。因为别的规则官方的，没发现过有些问题 发自我的iPhone
 …
  
为什么要清空节点？
 清空之后当然就是proxies missing了

**Comment by anjue39** [comment]
是的，这是我见过最好的规则，还有196行内那些dns fallback fifter



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月13日 09:58
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 几个问题咨询请教 (Issue #251)





 
虽然不知道官方的规则可以不报错，但是我这个规则正常用不会出错

**Comment by anjue39** [comment]
可以是0节点呀，规则策略是主要的，节点可有可无，可多可少可0才对



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月13日 09:57
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 几个问题咨询请教 (Issue #251)





  
我问这个，主要是你的rule在openclash订阅加载后，策略组和节点两部分，如果清空节点，保存应用，就会出现一个提示："Parse config error: proxy group[0]: use or proxies missing"。所以我想问你如果是网上某个规则，我去对一下，看是不是哪标点符号有问题。因为别的规则官方的，没发现过有些问题 发自我的iPhone
 …
  
为什么要清空节点？
 清空之后当然就是proxies missing了

**Comment by yu-steven** [comment]
> 可以是0节点呀，规则策略是主要的，节点可有可无，可多可少可0才对 clash格式里 proxies： 下面可以是空的呀。 可能这就是问题的原因，你不能为空 发自我的iPhone
> […](#)

我相信你如果用Windows版的clash把配置文件里的proxies字段删除会直接报错的

**Comment by yu-steven** [comment]
不报错才不正常

**Comment by anjue39** [comment]
我不太懂，但节点必须有，不能为空0的逻辑总觉得不对。我觉得它不叫模板，模板多是空的。你去看一下别的官方规则，都不内置节点。如果订阅不成，或者无节点可用就报错，我觉得是错误的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月13日 10:19
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 几个问题咨询请教 (Issue #251)





 
不报错才不正常

**Comment by yu-steven** [comment]
> 我不太懂，但节点必须有，不能为空0的逻辑总觉得不对。我觉得它不叫模板，模板多是空的。你去看一下别的官方规则，都不内置节点。如果订阅不成，或者无节点可用就报错，我觉得是错误的 发自我的iPhone
> […](#)

正常用呗，这种奇怪用法我还真没见过

**Comment by anjue39** [comment]
我试了别的规则，都是没服务器节点就只加载策略组或者第三方规则库什么的，也没报错。我又试了在线订阅，即便我不输入，它也能生成订阅



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月13日 10:19
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 几个问题咨询请教 (Issue #251)





 
不报错才不正常

**Comment by yu-steven** [comment]
> 我试了别的规则，都是没服务器节点就只加载策略组或者第三方规则库什么的，也没报错。我又试了在线订阅，即便我不输入，它也能生成订阅 发自我的iPhone
> […](#)

🤨🤨🤨

**Comment by anjue39** [comment]
这软件就得让你先添加策略组，我没办法，只能先订阅你的，然后去掉节点，只剩策略组



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月13日 10:27
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 几个问题咨询请教 (Issue #251)





  
我不太懂，但节点必须有，不能为空0的逻辑总觉得不对。我觉得它不叫模板，模板多是空的。你去看一下别的官方规则，都不内置节点。如果订阅不成，或者无节点可用就报错，我觉得是错误的 发自我的iPhone
 …
  
正常用呗，这种奇怪用法我还真没见过

**Comment by yu-steven** [comment]
> 这软件就得让你先添加策略组，我没办法，只能先订阅你的，然后去掉节点，只剩策略组 发自我的iPhone
> […](#)

啊这

**Comment by anjue39** [comment]
系统套用的策略规则文件，是在哪个文件定义的？

> ;去广告：支持
> ;自动测速：支持
> ;微软分流：支持
> ;苹果分流：支持
> ;**增强中国IP段**：不支持
> ;**增强国外GFW**：不支持

默认套用的模板 加粗部分支持吗

**Comment by yu-steven** [comment]
> 系统套用的策略规则文件，是在哪个文件定义的？
> 
> > ;去广告：支持
> > ;自动测速：支持
> > ;微软分流：支持
> > ;苹果分流：支持
> > ;**增强中国IP段**：不支持
> > ;**增强国外GFW**：不支持
> 
> 默认套用的模板 加粗部分支持吗

https://github.com/yu-steven/openit/blob/main/utils/subconverter/config/rule.ini

应该是支持的

**Comment by anjue39** [comment]
你哪个文件做到了把根目录下生成的订阅同步到你国内的服务器上的？

> Base64 https://openit.daycat.space/long
> 小火箭 https://openit.daycat.space/https
> Clash https://openit.daycat.space/clash
> Quanx https://openit.daycat.space/qx

**Comment by anjue39** [comment]
workflows我看你删除了几个文件，改名了两个文件，
[Update and rename Reuse.yaml to url1.yaml](https://github.com/yu-steven/openit/commit/41b6a3d01b842fdf52fada74c879fb22bcbf1102)
[Rename fix.yaml to url2.yaml](https://github.com/yu-steven/openit/commit/69c70e1e9737fa322bfbf79b5b7a740f0d34a791)
可是[Delete crontab.yml](https://github.com/yu-steven/openit/commit/ec2ad2ab8c67bf2a0f5e7b725a2c2c6a7d78627f)我有点不理解，这个文件是生成机场订阅的，删了怎么采集机场的，这个文件到底是做啥的，写着生成机场订阅，但其实我看代码是注册

**Comment by yu-steven** [comment]
> workflows我看你删除了几个文件，改名了两个文件，
> [Update and rename Reuse.yaml to url1.yaml](https://github.com/yu-steven/openit/commit/41b6a3d01b842fdf52fada74c879fb22bcbf1102)
> [Rename fix.yaml to url2.yaml](https://github.com/yu-steven/openit/commit/69c70e1e9737fa322bfbf79b5b7a740f0d34a791)
> 可是[Delete crontab.yml](https://github.com/yu-steven/openit/commit/ec2ad2ab8c67bf2a0f5e7b725a2c2c6a7d78627f)我有点不理解，这个文件是生成机场订阅的，删了怎么采集机场的，这个文件到底是做啥的，写着生成机场订阅，但其实我看代码是注册

是自动注册机场网站提取免费订阅的，两三个月前是有效的，现在生成的不好用了

**Comment by anjue39** [comment]
> > workflows我看你删除了几个文件，改名了两个文件，
> > [Update and rename Reuse.yaml to url1.yaml](https://github.com/yu-steven/openit/commit/41b6a3d01b842fdf52fada74c879fb22bcbf1102)
> > [Rename fix.yaml to url2.yaml](https://github.com/yu-steven/openit/commit/69c70e1e9737fa322bfbf79b5b7a740f0d34a791)
> > 可是[Delete crontab.yml](https://github.com/yu-steven/openit/commit/ec2ad2ab8c67bf2a0f5e7b725a2c2c6a7d78627f)我有点不理解，这个文件是生成机场订阅的，删了怎么采集机场的，这个文件到底是做啥的，写着生成机场订阅，但其实我看代码是注册
> 
> 是自动注册机场网站提取免费订阅的，两三个月前是有效的，现在生成的不好用了

只涉及几个节点，是吧，这个文件最后写着生成机场订阅，把我晃了一下子，顾名思义，我一开始以为这个文件是爬取免费节点的呢，其实不是，它只是提前注册个别几个自动注册的机场，主要爬取文件还是main.py

**Comment by anjue39** [comment]
> 你哪个文件做到了把根目录下生成的订阅同步到你国内的服务器上的？
> 
> > Base64 https://openit.daycat.space/long
> > 小火箭 https://openit.daycat.space/https
> > Clash https://openit.daycat.space/clash
> > Quanx https://openit.daycat.space/qx

这是我最想知道的，单独一个订阅文件放到国内服务器，不能自动更新没意义
github上的能自动更新，但是不同步
这两天我一直在研究这个事，最后我推理你估计国内服务器不只是clashcheck这个模块仅运行，三个模块都在运行，独立生成
github上只是代码和action演示，真正的订阅节点在你的国内服务器，是这样吗

**Comment by yu-steven** [comment]
> > 你哪个文件做到了把根目录下生成的订阅同步到你国内的服务器上的？
> > > Base64 https://openit.daycat.space/long
> > > 小火箭 https://openit.daycat.space/https
> > > Clash https://openit.daycat.space/clash
> > > Quanx https://openit.daycat.space/qx
> 
> 这是我最想知道的，单独一个订阅文件放到国内服务器，不能自动更新没意义 github上的能自动更新，但是做不到及时不同步，受制于cdn好坏 这两天我一直在研究这个事，最后我推理你估计国内服务器不只是clashcheck这个模块仅运行，三个模块都在运行，独立生成 github上只是代码和action演示，真正的订阅节点在你的国内服务器，是这样吗

订阅链接的服务使用的Cloudflare Workers
国内服务器时候clashcheck

**Comment by anjue39** [comment]
也就是说你那公开的订阅，其实不是在gihub接管生成的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月14日 11:01
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 几个问题咨询请教 (Issue #251)





   
你哪个文件做到了把根目录下生成的订阅同步到你国内的服务器上的？
  
Base64 https://openit.daycat.space/long
 小火箭 https://openit.daycat.space/https
 Clash https://openit.daycat.space/clash
 Quanx https://openit.daycat.space/qx
   
这是我最想知道的，单独一个订阅文件放到国内服务器，不能自动更新没意义 github上的能自动更新，但是做不到及时不同步，受制于cdn好坏 这两天我一直在研究这个事，最后我推理你估计国内服务器不只是clashcheck这个模块仅运行，三个模块都在运行，独立生成 github上只是代码和action演示，真正的订阅节点在你的国内服务器，是这样吗
  
订阅链接的服务使用的Cloudflare Workers
 国内服务器时候clashcheck

**Comment by yu-steven** [comment]
> 也就是说你那公开的订阅，其实不是在gihub接管生成的 发自我的iPhone
> […](#)

不是告诉你了吗，在GitHub生成的不准确需要国内服务器啊

**Comment by anjue39** [comment]
我说的是你pub的订阅链接的数据，不是github里生产出来的？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月14日 11:15
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 几个问题咨询请教 (Issue #251)





  
也就是说你那公开的订阅，其实不是在gihub接管生成的 发自我的iPhone
 …
  
不是告诉你了吗，在GitHub生成的不准确需要国内服务器啊

**Comment by anjue39** [comment]
> > > 你哪个文件做到了把根目录下生成的订阅同步到你国内的服务器上的？
> > > > Base64 https://openit.daycat.space/long
> > > > 小火箭 https://openit.daycat.space/https
> > > > Clash https://openit.daycat.space/clash
> > > > Quanx https://openit.daycat.space/qx
> > 
> > 
> > 这是我最想知道的，单独一个订阅文件放到国内服务器，不能自动更新没意义 github上的能自动更新，但是做不到及时不同步，受制于cdn好坏 这两天我一直在研究这个事，最后我推理你估计国内服务器不只是clashcheck这个模块仅运行，三个模块都在运行，独立生成 github上只是代码和action演示，真正的订阅节点在你的国内服务器，是这样吗
> 
> 订阅链接的服务使用的Cloudflare Workers 国内服务器只有clashcheck

![image](https://user-images.githubusercontent.com/98279987/195759364-bf54338a-e3b3-459c-b0fe-09bad3268d85.png)
选择红线第一个？

**Comment by yu-steven** [comment]
> > > > 你哪个文件做到了把根目录下生成的订阅同步到你国内的服务器上的？
> > > > > Base64 https://openit.daycat.space/long
> > > > > 小火箭 https://openit.daycat.space/https
> > > > > Clash https://openit.daycat.space/clash
> > > > > Quanx https://openit.daycat.space/qx
> > > 
> > > 
> > > 这是我最想知道的，单独一个订阅文件放到国内服务器，不能自动更新没意义 github上的能自动更新，但是做不到及时不同步，受制于cdn好坏 这两天我一直在研究这个事，最后我推理你估计国内服务器不只是clashcheck这个模块仅运行，三个模块都在运行，独立生成 github上只是代码和action演示，真正的订阅节点在你的国内服务器，是这样吗
> > 
> > 
> > 订阅链接的服务使用的Cloudflare Workers 国内服务器只有clashcheck
> 
> ![image](https://user-images.githubusercontent.com/98279987/195759364-bf54338a-e3b3-459c-b0fe-09bad3268d85.png) 选择红线第一个？

是的，但是如果没有生产需求订阅链接可以直接是GitHub的raw

**Comment by anjue39** [comment]
> > > > > 你哪个文件做到了把根目录下生成的订阅同步到你国内的服务器上的？
> > > > > > Base64 https://openit.daycat.space/long
> > > > > > 小火箭 https://openit.daycat.space/https
> > > > > > Clash https://openit.daycat.space/clash
> > > > > > Quanx https://openit.daycat.space/qx
> > > > 
> > > > 
> > > > 这是我最想知道的，单独一个订阅文件放到国内服务器，不能自动更新没意义 github上的能自动更新，但是做不到及时不同步，受制于cdn好坏 这两天我一直在研究这个事，最后我推理你估计国内服务器不只是clashcheck这个模块仅运行，三个模块都在运行，独立生成 github上只是代码和action演示，真正的订阅节点在你的国内服务器，是这样吗
> > > 
> > > 
> > > 订阅链接的服务使用的Cloudflare Workers 国内服务器只有clashcheck
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/98279987/195759364-bf54338a-e3b3-459c-b0fe-09bad3268d85.png) 选择红线第一个？
> 
> 是的，但是如果没有生产需求订阅链接可以直接是GitHub的raw

试过了，(https://raw.githubusercontent.com/yu-steven/openit/main/Clash.yaml)这样的，得在翻墙环境下，才能订阅成功

补问一个问题：
![Uploading WechatIMG819.png…]()

**Comment by anjue39** [comment]
你说的很中肯，翻墙环境下用raw就行。我已按照你的提示在cloudf里部署，等生效。发现国外的比国内的好太多，虽然可能慢点。从你的回复中get到很多思路和新鲜的东西。这些天对于你pcrs的架构现在很清晰了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月14日 12:01
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 几个问题咨询请教 (Issue #251)





     
你哪个文件做到了把根目录下生成的订阅同步到你国内的服务器上的？
  
Base64 https://openit.daycat.space/long
 小火箭 https://openit.daycat.space/https
 Clash https://openit.daycat.space/clash
 Quanx https://openit.daycat.space/qx
   
这是我最想知道的，单独一个订阅文件放到国内服务器，不能自动更新没意义 github上的能自动更新，但是做不到及时不同步，受制于cdn好坏 这两天我一直在研究这个事，最后我推理你估计国内服务器不只是clashcheck这个模块仅运行，三个模块都在运行，独立生成 github上只是代码和action演示，真正的订阅节点在你的国内服务器，是这样吗
  
订阅链接的服务使用的Cloudflare Workers 国内服务器只有clashcheck
  
 选择红线第一个？
  
是的，但是如果没有生产需求订阅链接可以直接是GitHub的raw

**Comment by yu-steven** [comment]
> 你说的很中肯，翻墙环境下用raw就行。我已按照你的提示在cloudf里部署，等生效。发现国外的比国内的好太多，虽然可能慢点。从你的回复中get到很多思路和新鲜的东西。这些天对于你pcrs的架构现在很清晰了 发自我的iPhone
> […](#)

👌

**Comment by yu-steven** [comment]
> 补问一个问题： ![image](https://user-images.githubusercontent.com/98279987/195760974-362b60ff-8770-4cfc-8a31-6e24c6ed016a.png)

URL重定向
状态码是301 / 302
主订阅 daycat.space 就是用到了重定向，这样一来可以避免被攻击后无法立刻恢复的问题

**Comment by anjue39** [comment]
> > 你说的很中肯，翻墙环境下用raw就行。我已按照你的提示在cloudf里部署，等生效。发现国外的比国内的好太多，虽然可能慢点。从你的回复中get到很多思路和新鲜的东西。这些天对于你pcrs的架构现在很清晰了 发自我的iPhone
> > […](#)
> 
> 👌

做了worker后，出现这样的地址https://git.123.workers.dev/，直接打开用不了，后面加github地址？？

**Comment by anjue39** [comment]
> > 补问一个问题： ![image](https://user-images.githubusercontent.com/98279987/195760974-362b60ff-8770-4cfc-8a31-6e24c6ed016a.png)
> 
> URL重定向 状态码是301 / 302 主订阅 daycat.space 就是用到了重定向，这样一来可以避免被攻击后无法立刻恢复的问题，现在你访问那个订阅链接会发现它会跳转到raw开头的网址

非翻墙环境，你那个https://openit.daycat.space/clash也打不开的

**Comment by anjue39** [comment]
![image](https://user-images.githubusercontent.com/98279987/195782856-fd835435-d28c-47a3-a177-bd9fd30f056e.png)
打不开

**Comment by anjue39** [comment]
今天你更新url2好频繁呀，楞是塞进去呀，从哪扒拉过来的

**Comment by yu-steven** [comment]
> 今天你更新url2好频繁呀，楞是塞进去呀，从哪扒拉过来的

自己看来源
然后
能不能不要把Issues当作Discussions啊

**Comment by yu-steven** [comment]
> ![image](https://user-images.githubusercontent.com/98279987/195782856-fd835435-d28c-47a3-a177-bd9fd30f056e.png)
> 打不开

因为你需要谷歌搜workers代理GitHub的教程
https://senjianlu.com/2021/12/cloudflare-workers-image/

**Comment by yu-steven** [comment]
如果你什么都不会的话请去谷歌取经，我这里只回答我仓库的相关问题，问多了就是浪费大家时间

**Comment by anjue39** [comment]
> 如果你什么都不会的话请去谷歌取经，我这里只回答我仓库的相关问题，问多了就是浪费你我的时间

收到，打扰了，我先关闭issues

**Comment by yu-steven** [comment]
👌
