### ISSUE TITLE
F: 类似以下clash格式不换行问题，可以按如下处理

### ISSUE THREAD

**Issue by anjue39** [yu-steven/openit#253]
### 详细说明

```bash
https://www.prop.cf/?name=paimon&client=clash
这里面是不换行的节点，程序代码可以加个判断，如果有这种情况，那么就批量替换如下图，这样就会解决，多加个回车符的事
这样可以应对一些类似情况不能处理的节点源，多多益善
```
![image](https://user-images.githubusercontent.com/98279987/195981903-72c3ffc2-c2c1-4de5-ac05-ec02f3b027a6.png)

**Comment by yu-steven** [comment]
这个订阅牵涉版权，所以删除

**Comment by anjue39** [comment]
欧了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月15日 19:15
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] F: 类似以下clash格式不换行问题，可以按如下处理 (Issue #253)





 
这个订阅牵涉版权，所以删除
