### ISSUE TITLE
近几天一直出现这个错误

### ISSUE THREAD

**Issue by anjue39** [yu-steven/openit#256]
![image](https://user-images.githubusercontent.com/98279987/197146235-e250aef1-02fe-4c6f-b13f-21d01cc04ad0.png)
本地近两天出现的错误，请修复！

**Comment by anjue39** [comment]
![Uploading 96B865A0-D001-4CC6-BE4C-92CE63FBE606.jpeg…]()
这可能有问题，cleanup你删了

**Comment by anjue39** [comment]
![7C4B02F4-209A-4B21-A768-E8FC573ED57C](https://user-images.githubusercontent.com/98279987/197256709-c473ddc2-8ffb-4dd4-bd64-42775008c7ae.jpeg)
这可能有问题，cleanup你删了

**Comment by yu-steven** [comment]
好的，我趣修一下

**Comment by yu-steven** [comment]
Emmmmmm
但是我觉得我没有弄错
你应该`git pull` 和 `docker build` again

**Comment by yu-steven** [comment]
可能是你git clone了我某个正在维修的时刻的拉取了

**Comment by anjue39** [comment]
刚回来看到。我再试试

**Comment by anjue39** [comment]
1.wehook的post请求是由什么事件触发的？是本地服务器的事件触发的？
2.wehook需要有类似crontab的定时自定义脚本吗？
3.如我以前所说的那种增加while.sh的需求，比如可以做到每间歇35分钟，自动本地服务器clashcheck运行4分钟一个批次，只要开始有sleep事件，说明有一个反复测试4分钟相对准确的的check.yaml成熟了，那么就触发cUrl产生post事件，nodes.yaml开始运行诞生新一次订阅。这样可以吗？
4.wehook代码可以公开学习一下吗

**Comment by anjue39** [comment]
https://github.com/yu-steven/openit/blob/d90419412fab4f067ca6f1f0e124d75be895e657/.github/workflows/Nodes.yaml#L51

重复两次命令是为什么？获取本地check.yaml文件到仓库也设定超时time out有意义？？？
