### ISSUE TITLE
连着五天更新失败了    大佬救命

### ISSUE THREAD

**Issue by smilencecc** [yu-steven/openit#257]
### 出现问题的订阅链接

https://openit.daycat.space/clash

### 你使用的是哪个应用程序？

Clash for Windows

### 复现方式

```bash
Clash订阅链接更新失败，挂梯子更新失败  机场的梯子也更新失败  关闭系统代理直接更新也失败
failed with error:Network Error

五天 五天啊   知道这五天我是怎么过来的吗
```

**Comment by smilencecc** [comment]
> 

![Uploading 756.png…]()
![Uploading 08.png…]()

**Comment by smilencecc** [comment]
> 

![756](https://user-images.githubusercontent.com/77428601/197337914-a91d60c1-8dc0-402e-989b-c0c0028235e6.png)
![Uploading 08.png…]()

**Comment by smilencecc** [comment]
> 

![756](https://user-images.githubusercontent.com/77428601/197337914-a91d60c1-8dc0-402e-989b-c0c0028235e6.png)
![08](https://user-images.githubusercontent.com/77428601/197337918-882e9c65-a600-40c8-99da-37b0e6f3d90f.png)

**Comment by yu-steven** [comment]
兄弟，订阅链接需要挂代理

**Comment by smilencecc** [comment]
> 兄弟，订阅链接需要挂代理

更新订阅链接的时候挂着代理也会失败

**Comment by smilencecc** [comment]
> 兄弟，订阅链接需要挂代理

![4](https://user-images.githubusercontent.com/77428601/197340829-b1498b12-4760-4989-b574-487d4bf26f77.png)

**Comment by yu-steven** [comment]
> > 兄弟，订阅链接需要挂代理
> 
> 更新订阅链接的时候挂着代理也会失败

换链接
https://openit.daycat.space/guide/domains.html

**Comment by smilencecc** [comment]
> > > 兄弟，订阅链接需要挂代理
> > 
> > 
> > 更新订阅链接的时候挂着代理也会失败
> 
> 换链接 https://openit.daycat.space/guide/domains.html

大佬骚等  我试试

**Comment by smilencecc** [comment]
> > > 兄弟，订阅链接需要挂代理
> > 
> > 
> > 更新订阅链接的时候挂着代理也会失败
> 
> 换链接 https://openit.daycat.space/guide/domains.html

刚把所有能用的订阅都试了一遍   还是不行  没搞懂啥情况咋一直显示网络失败   
 我现在用的是直接从仓库代码clash.yaml里面直接复制过去的     复制过去的clash.yaml的节点ping出来都是有速度  但是连接速度非常慢   都是kb/s或者b/s的速度

**Comment by yu-steven** [comment]
> > > > 兄弟，订阅链接需要挂代理
> > > 
> > > 
> > > 更新订阅链接的时候挂着代理也会失败
> > 
> > 
> > 换链接 https://openit.daycat.space/guide/domains.html
> 
> 刚把所有能用的订阅都试了一遍 还是不行 没搞懂啥情况咋一直显示网络失败 我现在用的是直接从仓库代码clash.yaml里面直接复制过去的 复制过去的clash.yaml的节点ping出来都是有速度 但是连接速度非常慢 都是kb/s或者b/s的速度

那是你的vpn问题，速度是因为万人骑

**Comment by smilencecc** [comment]
> > > > > 兄弟，订阅链接需要挂代理
> > > > 
> > > > 
> > > > 更新订阅链接的时候挂着代理也会失败
> > > 
> > > 
> > > 换链接 https://openit.daycat.space/guide/domains.html
> > 
> > 
> > 刚把所有能用的订阅都试了一遍 还是不行 没搞懂啥情况咋一直显示网络失败 我现在用的是直接从仓库代码clash.yaml里面直接复制过去的 复制过去的clash.yaml的节点ping出来都是有速度 但是连接速度非常慢 都是kb/s或者b/s的速度
> 
> 那是你的vpn问题，速度是因为万人骑

换了十一个订阅都更新不了   这个  有点夸张。。。

大佬能不能搞个不用代理也能更新的订阅   那样应该能达到十万人骑的级别  

![33](https://user-images.githubusercontent.com/77428601/197344598-9abb5e1f-f6a6-4c45-8c08-1f309b8d5fc9.png)

**Comment by smilencecc** [comment]
> > > > > 兄弟，订阅链接需要挂代理
> > > > 
> > > > 
> > > > 更新订阅链接的时候挂着代理也会失败
> > > 
> > > 
> > > 换链接 https://openit.daycat.space/guide/domains.html
> > 
> > 
> > 刚把所有能用的订阅都试了一遍 还是不行 没搞懂啥情况咋一直显示网络失败 我现在用的是直接从仓库代码clash.yaml里面直接复制过去的 复制过去的clash.yaml的节点ping出来都是有速度 但是连接速度非常慢 都是kb/s或者b/s的速度
> 
> 那是你的vpn问题，速度是因为万人骑


其他的订阅都能更新  就这两个链接更新失败。。

![111](https://user-images.githubusercontent.com/77428601/197369655-afc75863-3a59-4d9b-b555-c4a10c97ef0c.png)

**Comment by yu-steven** [comment]
> > > > > > 兄弟，订阅链接需要挂代理
> > > > > 
> > > > > 
> > > > > 更新订阅链接的时候挂着代理也会失败
> > > > 
> > > > 
> > > > 换链接 https://openit.daycat.space/guide/domains.html
> > > 
> > > 
> > > 刚把所有能用的订阅都试了一遍 还是不行 没搞懂啥情况咋一直显示网络失败 我现在用的是直接从仓库代码clash.yaml里面直接复制过去的 复制过去的clash.yaml的节点ping出来都是有速度 但是连接速度非常慢 都是kb/s或者b/s的速度
> > 
> > 
> > 那是你的vpn问题，速度是因为万人骑
> 
> 其他的订阅都能更新 就这两个链接更新失败。。
> 
> ![111](https://user-images.githubusercontent.com/77428601/197369655-afc75863-3a59-4d9b-b555-c4a10c97ef0c.png)

换备用域名

**Comment by smilencecc** [comment]
> > > > > > > 兄弟，订阅链接需要挂代理
> > > > > > 
> > > > > > 
> > > > > > 更新订阅链接的时候挂着代理也会失败
> > > > > 
> > > > > 
> > > > > 换链接 https://openit.daycat.space/guide/domains.html
> > > > 
> > > > 
> > > > 刚把所有能用的订阅都试了一遍 还是不行 没搞懂啥情况咋一直显示网络失败 我现在用的是直接从仓库代码clash.yaml里面直接复制过去的 复制过去的clash.yaml的节点ping出来都是有速度 但是连接速度非常慢 都是kb/s或者b/s的速度
> > > 
> > > 
> > > 那是你的vpn问题，速度是因为万人骑
> > 
> > 
> > 其他的订阅都能更新 就这两个链接更新失败。。
> > ![111](https://user-images.githubusercontent.com/77428601/197369655-afc75863-3a59-4d9b-b555-c4a10c97ef0c.png)
> 
> 换备用域名

最后这张图的输入栏里面就是备用域名  红色的Error   下载失败   也是网络错误

**Comment by yu-steven** [comment]
> > > > > > > > 兄弟，订阅链接需要挂代理
> > > > > > > 
> > > > > > > 
> > > > > > > 更新订阅链接的时候挂着代理也会失败
> > > > > > 
> > > > > > 
> > > > > > 换链接 https://openit.daycat.space/guide/domains.html
> > > > > 
> > > > > 
> > > > > 刚把所有能用的订阅都试了一遍 还是不行 没搞懂啥情况咋一直显示网络失败 我现在用的是直接从仓库代码clash.yaml里面直接复制过去的 复制过去的clash.yaml的节点ping出来都是有速度 但是连接速度非常慢 都是kb/s或者b/s的速度
> > > > 
> > > > 
> > > > 那是你的vpn问题，速度是因为万人骑
> > > 
> > > 
> > > 其他的订阅都能更新 就这两个链接更新失败。。
> > > ![111](https://user-images.githubusercontent.com/77428601/197369655-afc75863-3a59-4d9b-b555-c4a10c97ef0c.png)
> > 
> > 
> > 换备用域名
> 
> 最后这张图的输入栏里面就是备用域名 红色的Error 下载失败 也是网络错误

你复制到订阅栏的链接是需要你去查看的网页而不是订阅，请您把复制到clash的那个链接复制到浏览器里并点击回车即可浏览网页，网页内有您需要域名和订阅的

**Comment by yu-steven** [comment]
如何您确实看不懂或者不想用脑子思考的话，您可以使用绿头的订阅，因为绿头的订阅就是重定向到openit的订阅链接
