### ISSUE TITLE
F: 希望大佬能不能添加一个TikTok的网络选择选项

### ISSUE THREAD

**Issue by Poker-Pan** [yu-steven/openit#259]
### 详细说明

```bash
希望大佬能不能添加一个TikTok的网络选择选项，因为ios下载的是美区的TikTok  然后网络连接到时候自动选择，很多时候打不开，希望能和youtubue netflix 一样的有个单独的选择项   感谢大佬
```

**Comment by Poker-Pan** [comment]
- name: 🌱 TikTok
    type: select
    proxies:
      - DIRECT
      - 🚀 全局设置
      - ♻️ 自动选择
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 新加坡节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🇰🇷 韩国节点



 - DOMAIN-SUFFIX,tiktok.com,🌱 TikTok
 - DOMAIN-SUFFIX,tiktokcdn.com,🌱 TikTok
 - DOMAIN-SUFFIX,tiktokv.com,🌱 TikTok
 - DOMAIN-KEYWORD,tiktok,🌱 TikTok
 - DOMAIN-KEYWORD,tiktokcdn-,🌱 TikTok

**Comment by Poker-Pan** [comment]
感谢大佬

**Comment by yu-steven** [comment]
OK

**Comment by yu-steven** [comment]
不对啊，我就说我配置了TikTok了啊，但是我还是补充了你提供的规则到我之前的tiktok规则里了
TikTok rule
https://github.com/yu-steven/openit/blob/main/sub/rule/TikTok.list
在subconverter里的配置文件(ini)
https://github.com/yu-steven/openit/blob/fa85a7ad23f4f385514d19cacaa931bb4e1105ff/utils/subconverter/config/rule.ini#L53

**Comment by Poker-Pan** [comment]
我刚刚也看到了这个rule  我是用的clash订阅的方式在ipad上使用的   今天更新了一下订阅  发现没有这个选项  分流规则里也没有变      是不是还得麻烦大佬更新一下订阅的配置   感谢

**Comment by Poker-Pan** [comment]
So sorry  我找到原因了  用了订阅转换  然后没了  非常感谢大佬

**Comment by yu-steven** [comment]
啊这

**Comment by Poker-Pan** [comment]
不用转换 每次更新都得挂着别的梯子才能更新openit

**Comment by Poker-Pan** [comment]
想到一个办法  解决了  曲线救国 搞两个订阅  哈哈   感谢大佬的帮助  👍

**Comment by yu-steven** [comment]
其实你也可以在订阅转换里的config=后面引用我的subconverter适配的ini配置文件
https://raw.githubusercontent.com/yu-steven/openit/main/utils/subconverter/config/rule.ini
就像这样
https://api.tsutsu.one/sub?target=clash&url=ss%3A%2F%2Fnodes&insert=false&config=https://raw.githubusercontent.com/yu-steven/openit/main/utils/subconverter/config/rule.ini
就可以啦

**Comment by Poker-Pan** [comment]
好的 好的  我在摸索一下  但是现在用APP 还是刷新不出视频   还不知道是哪儿出问题了 我在弄弄 哈哈
