### ISSUE TITLE
nodes.yaml出现check.yaml找不到的错误、出现生效pool/config.yaml回环订阅就会失败的错误

### ISSUE THREAD

**Issue by anjue39** [yu-steven/openit#260]
```bash
nodes.yaml出现check.yaml找不到的错误、出现只要pool/config.yaml里回环订阅就会失败的错误
```
![image](https://user-images.githubusercontent.com/98279987/197486151-3659f8d4-31c3-45dc-9efd-35c1a2cbd04e.png)
最近一周改动频繁，代码出现很多前后对应不上的错误
比如上面错误，本地上传check.yaml那种是没问题的，但是仓库原始那种，代码里可能input.yaml未转到clashcheck目录生成check.yaml

**Comment by yu-steven** [comment]
修好了

**Comment by anjue39** [comment]
> 修好了

我现在去试
