### ISSUE TITLE
获取check.yaml文件到仓库也设定超时time out有什么意义？

### ISSUE THREAD

**Issue by anjue39** [yu-steven/openit#261]
https://github.com/yu-steven/openit/blob/d90419412fab4f067ca6f1f0e124d75be895e657/.github/workflows/Nodes.yaml#L51

重复两次命令是为什么？获取本地check.yaml文件到仓库也设定超时time out有意义？？？

**Comment by yu-steven** [comment]
怕wget超时重试无响应

**Comment by anjue39** [comment]
![image](https://user-images.githubusercontent.com/98279987/197606883-5aa77224-6085-4927-8b56-3e53ea61cb2e.png)

**Comment by anjue39** [comment]
![image](https://user-images.githubusercontent.com/98279987/197612649-bc1ab3a8-03e2-41b9-a432-edda5cf23375.png)
本地生产有问题，请;xqfu
路径有问题，因clashcheck模块在本地为单独模块，data/文件夹下无input.yaml

**Comment by yu-steven** [comment]
> ![image](https://user-images.githubusercontent.com/98279987/197612649-bc1ab3a8-03e2-41b9-a432-edda5cf23375.png)
> 本地生产有问题，请修复
> 路径有问题，因clashcheck模块在本地为单独模块，data/文件夹下无input.yaml

啸死，你不会看配置文件备注吗还是你看不懂啊

**Comment by yu-steven** [comment]
注释里的source后边标注了

https://github.com/yu-steven/openit/blob/25aa3b2f010c508c4f80fe0a6302db61c1e58212/utils/clashcheck/data/config.yaml#L4

**Comment by yu-steven** [comment]
> ![image](https://user-images.githubusercontent.com/98279987/197606883-5aa77224-6085-4927-8b56-3e53ea61cb2e.png)

是这样的，出错就出错吧，我也没办法
