### ISSUE TITLE
Webhook的确更精准，我们也可以用了？能不能readme里做个说明如何使用

### ISSUE THREAD

**Issue by anjue39** [yu-steven/openit#262]
### 详细说明

```bash
Webhook的确更精准，我们也可以用了吗？如果可以，能不能readme里做个说明如何使用，webhook需要做脚本吗
```

**Comment by yu-steven** [comment]
https://github.com/yu-steven/openit/blob/a41483061e6985934cbbfb0a1d95962c25ccd0da/.github/workflows/Nodes.yaml#L11

**Comment by anjue39** [comment]
> https://github.com/yu-steven/openit/blob/a41483061e6985934cbbfb0a1d95962c25ccd0da/.github/workflows/Nodes.yaml#L11-L13

![image](https://user-images.githubusercontent.com/98279987/197503845-0d504cb9-e677-48ec-8ce5-9ac0e0e3d3cd.png)

**Comment by yu-steven** [comment]
> > https://github.com/yu-steven/openit/blob/a41483061e6985934cbbfb0a1d95962c25ccd0da/.github/workflows/Nodes.yaml#L11-L13
> 
> ![image](https://user-images.githubusercontent.com/98279987/197503845-0d504cb9-e677-48ec-8ce5-9ac0e0e3d3cd.png)

我这注释里有个链接没看见吗，就知道问？？？

**Comment by anjue39** [comment]
https://github.com/yu-steven/openit/blob/bb71d8fb94be210488794393255e4ce96deac3ba/.github/webhook.sh#L2

wehook只能设定固定的45分钟的间隔？而不能像crontab那样的机制可以具体设定不同的日期更加细化的时间间隔？

**Comment by anjue39** [comment]
![image](https://user-images.githubusercontent.com/98279987/197567686-3ddfdd00-e63d-42b7-9c45-b516ebf47708.png)
webhook整个运行过程是不是这样，以上都正确吗
再次问触发事件到底是什么才会让它工作触发

- [ ] 都正确
- [ ] 部分正确

**Comment by yu-steven** [comment]
> https://github.com/yu-steven/openit/blob/bb71d8fb94be210488794393255e4ce96deac3ba/.github/webhook.sh#L2
> 
> wehook的时间间隔在哪里设置？其实我一直问它的触发事件到底是什么？什么样的事件才会让wehook开始触发。能像crontab那样的机制可以具体设定不同的日期更加细化的时间间隔吗？

crontab就是crontab，可以很细化的触发事件，但是GitHub Action的crontab不是很准时
webhook如果可以像crontab一样触发的话那我早就不用crontab了

**Comment by yu-steven** [comment]
> ![image](https://user-images.githubusercontent.com/98279987/197567686-3ddfdd00-e63d-42b7-9c45-b516ebf47708.png) webhook整个运行过程是不是这样，以上都正确吗 总觉得还差一个重要的控制时间的json脚本文件才齐活 再次问触发事件到底是什么才会让它工作触发
> 
> * [ ]  都正确
> * [ ]  部分正确

触发事件由webhook.sh的curl命令触发

**Comment by yu-steven** [comment]
curl通过向指定的链接POST指定的文件json格式的密钥和type即可触发事件

**Comment by anjue39** [comment]
curl  -X POST -d 'name=张三'  https://api.github.com/repos/yu-steven/openit/dispatches
如果只是这样简单的crul触发，可以运行吗？

[webhook](https://github.com/yu-steven/openit/blob/6d5f7ec99878113f8885c474f7258c4caa4c89ae/.github/webhook.sh#L3)
这不是一直间隔45秒发送一次嘛，难道45秒就后台运行一次？？？

**Comment by anjue39** [comment]
现在我几乎快看明白了，
如你所说，crontab可以细化，但不准时，wehook无所谓准时，只要触发就干活
如果只是简单的比如我1小时准时运行一次，要求严格就用webhool，设置sleep 3600，如果要求不严格，用crontab也可以，1小时左右呗

其实1小时左右运行一次就行了，半天运行一次也够用，这两种机制其实按刚才说的也没多大区别
但是，我有个建议是，全程最重要的一个文件就是check.yaml，用webhook机制，只要一产生check.yaml，就由代码控制自动发送curl发送 那样指定的表头的请求，运行my job，产生一次订阅，如果非要给时间做个间隔限制，那就对check.yaml做手脚，如以前所说的 whil.sh和start.sh双重利用time out和sleep，也能搞定

如果对准时敏感，那可以把一周时间不同时间段做出不同type的webhook呀，webhook1，就是周一，webook1-5就是周一至周五，webook67就是周六日，if nowtime是，那么自动判断执行webhook几，就行

**Comment by anjue39** [comment]
如果再科学一点，其实还是要对clashcheck诞生的check.yaml跟踪，if do循环连续10次，check.yaml里对比10次里的第一次重复率或者改动率不超过50%，then sleep 2h，保留最后结果一次，歇2小时，反正节点源动静也不大。else if超过50%改动，then sleep 30m，注意有动静，可密切关注，30分钟后再来一次，这样的do循环10次为一个批次，来通过节点源上新或者重复率多少来决定干活是该歇歇还是该加班。只要有check.yaml出来，wehook就赶紧发出指令，my job开始搞过来加工，产生一次订阅

**Comment by yu-steven** [comment]
随你，但是这里我的方法是在action的配置文件里利用curl命令自动在Nodes.yaml运动完后触发Webhook

**Comment by anjue39** [comment]
> 随你，但是这里我的方法是在action的配置文件里利用curl命令自动在Nodes.yaml运行完后触发Webhook
> 
> https://github.com/yu-steven/openit/blob/6d5f7ec99878113f8885c474f7258c4caa4c89ae/.github/workflows/Nodes.yaml#L84-L89

可你这固定45秒运行一次呀

**Comment by anjue39** [comment]
https://github.com/yu-steven/openit/blob/6d5f7ec99878113f8885c474f7258c4caa4c89ae/.github/webhook.sh#L3
这里的token $1"，确认这样就行？而不是token ${{ secrets.webhook }}？

**Comment by yu-steven** [comment]
由于外部shell脚本不能接收到action的秘密变量所以你可以看Nodes.yaml的引用这个脚本后面带了个参数，参数就是那个secret，shell脚本想引入这个参数就是用 `$1` 引用，后面如果有第二个参数就是用 `$2` 引用，以此类推，`$0` 保留为命令本身

**Comment by yu-steven** [comment]
> > 随你，但是这里我的方法是在action的配置文件里利用curl命令自动在Nodes.yaml运行完后触发Webhook
> > https://github.com/yu-steven/openit/blob/6d5f7ec99878113f8885c474f7258c4caa4c89ae/.github/workflows/Nodes.yaml#L84-L89
> 
> 你设计的挺好，可你这固定45秒运行一次呀，运行一次nodes.yaml就需要几分钟，还没生产出来，你这45秒就又发送post请求了，这不科学呀

45s可以改成1m的也就是一分钟，2h就是两个小时

**Comment by yu-steven** [comment]
还有这个POST请求你可以看到在第85行由一个`needs`，这控制着这个curl命令只在第一个自动化运行完后运行，确保了完全搜集筛选后触发下一次

**Comment by anjue39** [comment]
> 还有这个POST请求你可以看到在第85行有一个`needs`，这控制着这个curl命令只在第一个自动化运行完后运行，确保了完全搜集筛选后触发下一次

似的，我调试成功了。你刚才说的如我思维导图里说的那样，运行一次max job后自动通过curl触发下一次，确实你sleep多久就是多久。只是action里有两个job看起来略显累赘

**Comment by yu-steven** [comment]
> > 还有这个POST请求你可以看到在第85行有一个`needs`，这控制着这个curl命令只在第一个自动化运行完后运行，确保了完全搜集筛选后触发下一次
> 
> 似的，我调试成功了。你刚才说的如我思维导图里说的那样，运行一次max job后自动通过curl触发下一次，确实你sleep多久就是多久。只是action里有两个job看起来略显累赘

你也可以把两个job合并起来，把第二个job的run部分放到上面，这样虽然不太清晰，但是会减轻累赘

**Comment by anjue39** [comment]
没错！我一开始不了解webhook，以为你本地有一个更优于crontab的触发机制，猜想只要check.yaml产生就会触发。我想多了，原来就是一条curl命令，优点也只是准时，做不到细密。我不问你不行，卡壳了，注释那个资料我看了，我以为核心是后台你有个json脚本呢。如果不是你做个自动脚本，它也不是自动的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月25日 01:46
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] Webhook的确更精准，我们也可以用了？能不能readme里做个说明如何使用 (Issue #262)





   
还有这个POST请求你可以看到在第85行有一个needs，这控制着这个curl命令只在第一个自动化运行完后运行，确保了完全搜集筛选后触发下一次
  
似的，我调试成功了。你刚才说的如我思维导图里说的那样，运行一次max job后自动通过curl触发下一次，确实你sleep多久就是多久。只是action里有两个job看起来略显累赘
  
你也可以把两个job合并起来，把第二个job的run部分放到上面，这样虽然不太清晰，但是会减轻累赘

**Comment by yu-steven** [comment]
> 没错！我一开始不了解webhook，以为你本地有一个更优于crontab的触发机制，猜想只要check.yaml产生就会触发。我想多了，原来就是一条curl命令，优点也只是准时，做不到细密。我不问你不行，卡壳了，注释那个资料我看了，我以为核心是后台你有个json脚本呢。如果不是你做个自动脚本，它也不是自动的 发自我的iPhone
> […](#)

❤️

**Comment by anjue39** [comment]
还是发现2个问题，觉得有必要跟你说一下，可能sleep代码的位置需要调一下，因为测试中发现以下现象
1.如果修改了webhook.sh里的sleep时间间隔，它是不会生效的，除非cancel掉workflow，重新运行nodes.yaml才会生效。
2.我现在设置的时间间隔是 sleep 2000，发现它运行完max job第一项job后，就一直转圈圈，等着下一项curl命令，在action中就像假死了一样。如下图
![image](https://user-images.githubusercontent.com/98279987/197599014-2b6398b4-2e65-46b9-ade1-8942f036c385.png)
![image](https://user-images.githubusercontent.com/98279987/197599173-9a5e272e-aa66-4e8b-80dd-a506b7399e74.png)
![image](https://user-images.githubusercontent.com/98279987/197599402-45c67bac-3594-4e84-8eee-eb89cac561c1.png)

https://github.com/yu-steven/openit/blob/a9ccba3a1ba0448032945278a5c1a47808f66d3c/.github/webhook.sh#L2
这行sleep的代码放在job中，它也是一个其中一个未完的改成，我觉得放在这不合适，实际是想让它完成后，消停2000秒，而不是让它转圈圈等2000秒

**Comment by anjue39** [comment]
1.如果手动触发，在其他电脑就输入下面的？
 curl -X POST https://api.github.com/repos/yu-steven/openit/dispatches -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token **_真正的token值_**" --data '{"event_type": "Webhook"}' --silent 

2.token值那还输入$1，有效吗？

3.如果不想自动触发，纯手动curl触发，代码该如何改动
