### ISSUE TITLE
这样的逻辑是错的，一个sleep的中间过程让一个事件一直不结束

### ISSUE THREAD

**Issue by anjue39** [yu-steven/openit#264]
再次伶出来反馈，作者不觉得有问题吗？

以下引用反馈过未被关注的原文：
还是发现2个问题，觉得有必要说一下，可能sleep代码的位置需要调一下，因为测试中发现以下现象
1.如果修改了webhook.sh里的sleep时间间隔，它是不会生效的，除非cancel掉workflow，重新运行nodes.yaml才会生效。
2.我现在设置的时间间隔是 sleep 2000，发现它运行完max job第一项job后，就一直转圈圈，等着下一项curl命令，在action中就像假死了一样。如下图
![image](https://user-images.githubusercontent.com/98279987/197599014-2b6398b4-2e65-46b9-ade1-8942f036c385.png)
![image](https://user-images.githubusercontent.com/98279987/197599173-9a5e272e-aa66-4e8b-80dd-a506b7399e74.png)
![image](https://user-images.githubusercontent.com/98279987/197599402-45c67bac-3594-4e84-8eee-eb89cac561c1.png)

https://github.com/yu-steven/openit/blob/a9ccba3a1ba0448032945278a5c1a47808f66d3c/.github/webhook.sh#L2
这行sleep的代码放在job中，它也是其中一个未完的过程项，它就是设置休眠2天，整个工作也是在进行，我觉得放在这不合适，实际是想让它完成后，消停2000秒，而不是让它转圈圈等2000秒。你无论设45秒还是设置15m分钟，逻辑都是错的，休眠不应该在这个事件中充当间隔时间。总之，不能用sleep来充当事件中的批次间隔。你设置这个的本意是让max job彻底先完成，给它一个缓冲时间，但其实没必要。这个sleep不能当做间隔时间，里面含两个事：一个是max job，一个是webhook，这两件事事完了再sleep。我说的是意思是：30分钟自动运行一次，运行完彻底停止，等30分钟再来一次。
---
正确的逻辑：真正触发事件是本地check.yaml的产生，对clashcheck模块进行时间限定，比如只爬取4分钟，这个时候通报webhook开始干活，给转入下面流程一个缓冲时间，这个期间clashcheck模块可以sleep 2分钟，4+2=6分钟后，webhook触发到的nodes.yaml其他流程已有时间采集到check.yaml，6分钟后，kill掉clashcheck模块运行，再对以上这个完整的闭环过程 do循环，对do循环设置间隔时间

**Comment by yu-steven** [comment]
那你是觉得资源被浪费了还是只是不想按照这样的逻辑去运行呢
如果是前者，那你再换别的方法吧
如果是后者，那又是什么意思呢

**Comment by yu-steven** [comment]
> 不觉得有问题？第一个过程max job早已完成订阅，一个sleep和为了下一次自动化，整个nodes处于表面未完状态，不觉得别扭？ 发自我的iPhone
> […](#)

基本逻辑是上一个自动化循环运行完事后紧接着运行下一次循环，所以总是会有一个自动化循环在转圈圈，为了准确的控制事件封发生只能这样干咯

**Comment by anjue39** [comment]
![image](https://user-images.githubusercontent.com/98279987/198251634-0d12d246-3cd7-4a91-b207-16c8cad87e40.png)
出现以上错误

**Comment by yu-steven** [comment]
> ![image](https://user-images.githubusercontent.com/98279987/198251634-0d12d246-3cd7-4a91-b207-16c8cad87e40.png)
> 出现以上错误

字面意思，UUID不规范，属Clash配置文件错误

**Comment by anjue39** [comment]
> > ![image](https://user-images.githubusercontent.com/98279987/198251634-0d12d246-3cd7-4a91-b207-16c8cad87e40.png)
> > 出现以上错误
> 
> 字面意思，UUID不规范，属Clash配置文件错误

你的github里也开始出错了，一块儿查

**Comment by yu-steven** [comment]
> > > ![image](https://user-images.githubusercontent.com/98279987/198251634-0d12d246-3cd7-4a91-b207-16c8cad87e40.png)
> > > 出现以上错误
> > 
> > 
> > 字面意思，UUID不规范，属Clash配置文件错误
> 
> 你的github里也开始出错了，一块儿查

我看见了，找到问题了，正在修

**Comment by anjue39** [comment]
> > > > ![image](https://user-images.githubusercontent.com/98279987/198251634-0d12d246-3cd7-4a91-b207-16c8cad87e40.png)
> > > > 出现以上错误
> > > 
> > > 
> > > 字面意思，UUID不规范，属Clash配置文件错误
> > 
> > 
> > 你的github里也开始出错了，一块儿查
> 
> 我看见了，找到问题了，正在修

好的，补充一个错误日志
![image](https://user-images.githubusercontent.com/98279987/198255690-d2632c89-cff6-4640-b9f5-6e2c17bdc638.png)

**Comment by anjue39** [comment]
https://github.com/yu-steven/openit/blob/5731fc74494355e53295d67d2076c024bee0bb8a/utils/pool/pool.yaml#L2-L89

截取一个片段，这里面的openit.com的定义是哪个文件控制的？发现它与rm里config.js无关

**Comment by yu-steven** [comment]
> https://github.com/yu-steven/openit/blob/5731fc74494355e53295d67d2076c024bee0bb8a/utils/pool/pool.yaml#L2-L89
> 
> 截取一个片段，这里面的→ openitsub.com的定义是哪个文件控制的？发现它与rm里config.js无关

抱歉，那个箭头是名字

**Comment by anjue39** [comment]
> > https://github.com/yu-steven/openit/blob/5731fc74494355e53295d67d2076c024bee0bb8a/utils/pool/pool.yaml#L2-L89
> > 
> > 截取一个片段，这里面的→ openitsub.com的定义是哪个文件控制的？发现它与rm里config.js无关
> 
> 抱歉，那个箭头是名字

我知道箭头是名字，我是说带箭头的这个名字是哪个文件控制的？

**Comment by anjue39** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/98279987/198251634-0d12d246-3cd7-4a91-b207-16c8cad87e40.png)
> > > > > 出现以上错误
> > > > 
> > > > 
> > > > 字面意思，UUID不规范，属Clash配置文件错误
> > > 
> > > 
> > > 你的github里也开始出错了，一块儿查
> > 
> > 
> > 我看见了，找到问题了，正在修
> 
> 好的，补充一个错误日志 ![image](https://user-images.githubusercontent.com/98279987/198255690-d2632c89-cff6-4640-b9f5-6e2c17bdc638.png)

修好了？你只是注释了回环，我这边测试还不行

**Comment by yu-steven** [comment]
> > > https://github.com/yu-steven/openit/blob/5731fc74494355e53295d67d2076c024bee0bb8a/utils/pool/pool.yaml#L2-L89
> > > 
> > > 截取一个片段，这里面的→ openitsub.com的定义是哪个文件控制的？发现它与rm里config.js无关
> > 
> > 
> > 抱歉，那个箭头是名字
> 
> 我知道箭头是名字，我是说带箭头的这个名字是哪个文件控制的？

就是rm里的config.js

**Comment by anjue39** [comment]
> > > > https://github.com/yu-steven/openit/blob/5731fc74494355e53295d67d2076c024bee0bb8a/utils/pool/pool.yaml#L2-L89
> > > > 
> > > > 截取一个片段，这里面的→ openitsub.com的定义是哪个文件控制的？发现它与rm里config.js无关
> > > 
> > > 
> > > 抱歉，那个箭头是名字
> > 
> > 
> > 我知道箭头是名字，我是说带箭头的这个名字是哪个文件控制的？
> 
> 就是rm里的config.js

我测试了，那个文件，对它不管用

**Comment by yu-steven** [comment]
> > > > > https://github.com/yu-steven/openit/blob/5731fc74494355e53295d67d2076c024bee0bb8a/utils/pool/pool.yaml#L2-L89
> > > > > 
> > > > > 截取一个片段，这里面的→ openitsub.com的定义是哪个文件控制的？发现它与rm里config.js无关
> > > > 
> > > > 
> > > > 抱歉，那个箭头是名字
> > > 
> > > 
> > > 我知道箭头是名字，我是说带箭头的这个名字是哪个文件控制的？
> > 
> > 
> > 就是rm里的config.js
> 
> 我测试了，那个文件，对它不管用

当然不管用，因为docker只用来运行clashcheck

**Comment by yu-steven** [comment]
要是像用rm你需要安装npm环境，这个你自己弄

**Comment by anjue39** [comment]
我没用本地环境，在github里整个过程运行也不管用

**Comment by yu-steven** [comment]
> 我没用本地环境，在github里整个过程运行也不管用

哪里不管用

**Comment by anjue39** [comment]
> > 我没用本地环境，在github里整个过程运行也不管用
> 
> 哪里不管用

在github里用原nodes.yaml走全流程，rm/config.js里的自定义→ openitsub.com比如改成→ abc.com对上面提到的pool.yaml代码片段名字部分的无效，还是→ openitsub.com

**Comment by anjue39** [comment]
![image](https://user-images.githubusercontent.com/98279987/198356058-de950a44-93fb-4cd4-b2be-ce9698d59d77.png)
这一部分放入input.yaml的自定义节点库直接参与后面的clashcheck筛选？
或者放入已筛选好的check.yaml直接参与后面的rm等后续流程？

我是问，前面pool产生的out.yaml move和rename 到这个文件夹不会覆盖？先执行手动放进去的input.yaml或者check.yaml?

**Comment by anjue39** [comment]
我这里提一个进阶问题：

比如我找到了20个稳定的节点，不需要入库回炉，也不需要筛选，直接放入url参与订阅结果，但是只想最后的订阅只有这20个自定义的节点，没有url1，只有url2，有什么更好的简单的办法吗，也就是最后生成的各种订阅格式只有这20个，只是用了系统的rm和converter后面部分模块

**Comment by anjue39** [comment]
提两个发现的问题和建议：
问题：log日志，发现总是比实际少一条，比如2条，log日志是1条
建议：如下图
![image](https://user-images.githubusercontent.com/98279987/198390239-9c0c350a-7555-41df-b516-7639859a52ac.png)

**Comment by anjue39** [comment]
https://github.com/yu-steven/openit/blob/1099fc665c2d448d1f692d949781d4ce6ef4f539/.github/workflows/Nodes.yaml#L64
这条出来的结果1是啥东西，和url合并又成了啥

**Comment by yu-steven** [comment]
> > > 我没用本地环境，在github里整个过程运行也不管用
> > 
> > 
> > 哪里不管用
> 
> 在github里用原nodes.yaml走全流程，rm/config.js里的自定义→ openitsub.com比如改成→ abc.com对上面提到的pool.yaml代码片段名字部分的无效，还是→ openitsub.com

对上面的当然无效，因为pool.yaml是由根目录url触发的另一个自动化流程所产出的

**Comment by yu-steven** [comment]
> ![image](https://user-images.githubusercontent.com/98279987/198356058-de950a44-93fb-4cd4-b2be-ce9698d59d77.png) 这一部分放入input.yaml的自定义节点库直接参与后面的clashcheck筛选？ 或者放入已筛选好的check.yaml直接参与后面的rm等后续流程？
> 
> 我是问，前面pool产生的out.yaml move和rename 到这个文件夹不会覆盖？先执行手动放进去的input.yaml或者check.yaml?

对于input.yaml你既可以手动添加也可以通过自动化流程自动把output.yaml转移到此文件夹的input.yaml
对于为什么在clashcheck文件夹下我有毛病的又加了两个次级文件夹是因为要为将来在容器挂载数据卷做准备

**Comment by yu-steven** [comment]
> ### 2条bug+1条建议：
> `Bug1：log日志，发现总是比实际少一条，比如2条，log日志是1条` `Bug2：节点库有几条源已经失效，错误提示看workflow详情pool部分，有提示哪条源有错误`
> 
> _propose：如下图_ ![image](https://user-images.githubusercontent.com/98279987/198390239-9c0c350a-7555-41df-b516-7639859a52ac.png)

log当然少一条，因为第一行是`openit url`
失效我知道，我又不瞎，我在等它恢复

如果是功能上的建议，我可以做，但是我不是你雇的开发人员，虽然我确实没有写说明文档，但是你尽管问我问题我都会回答，但是你叫我帮你实现什么什么功能，你自己做行吗，谷歌搜一搜，思考思考什么的

**Comment by yu-steven** [comment]
> https://github.com/yu-steven/openit/blob/1099fc665c2d448d1f692d949781d4ce6ef4f539/.github/workflows/Nodes.yaml#L64
> 
> 
> 这条出来的结果1是啥东西，和url合并又成了啥

你可以把命令挑出来，进行逐行运行，我在这里一句话说不明白

**Comment by anjue39** [comment]
> > ![image](https://user-images.githubusercontent.com/98279987/198356058-de950a44-93fb-4cd4-b2be-ce9698d59d77.png) 这一部分放入input.yaml的自定义节点库直接参与后面的clashcheck筛选？ 或者放入已筛选好的check.yaml直接参与后面的rm等后续流程？
> > 我是问，前面pool产生的out.yaml move和rename 到这个文件夹不会覆盖？先执行手动放进去的input.yaml或者check.yaml?
> 
> 对于input.yaml你既可以手动添加也可以通过自动化流程自动把output.yaml转移到此文件夹的input.yaml 对于为什么在clashcheck文件夹下我有毛病的又加了两个次级文件夹是因为要为将来在容器挂载数据卷做准备

我想明确的是，如果文件夹中有手动的input.yaml或者check.yaml，也有自动化的流程，最后的结果是执行自动化的还是先执行文件夹里这两个文件

**Comment by anjue39** [comment]
> > > > 我没用本地环境，在github里整个过程运行也不管用
> > > 
> > > 
> > > 哪里不管用
> > 
> > 
> > 在github里用原nodes.yaml走全流程，rm/config.js里的自定义→ openitsub.com比如改成→ abc.com对上面提到的pool.yaml代码片段名字部分的无效，还是→ openitsub.com
> 
> 对上面的当然无效，因为pool.yaml是由根目录url触发的另一个自动化流程所产出的

url触发的那个管它的文件是哪个？

**Comment by anjue39** [comment]
多虑了，我只是建议。我也没那么大需求，只是提供一个你优化的方向角度



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月28日 08:30
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 这样的逻辑是错的，一个sleep的中间过程让一个事件一直不结束 (Issue #264)





  
2条bug+1条建议：
 
Bug1：log日志，发现总是比实际少一条，比如2条，log日志是1条 Bug2：节点库有几条源已经失效，错误提示看workflow详情pool部分，有提示哪条源有错误
 
propose：如下图 
  
log当然少一条，因为第一行是openit url
 失效我知道，我又不瞎，我在等它恢复
 
如果是功能上的建议，我可以做，但是我不是你雇的开发人员，虽然我确实没有写说明文档，但是你尽管问我问题我都会回答，但是你叫我帮你实现什么什么功能，你自己做行吗，谷歌搜一搜，思考思考什么的

**Comment by yu-steven** [comment]
> 多虑了，我只是建议。我也没那么大需求，只是提供一个你优化的方向角度 发自我的iPhone
> […](#)

好的👌

**Comment by yu-steven** [comment]
> > > ![image](https://user-images.githubusercontent.com/98279987/198356058-de950a44-93fb-4cd4-b2be-ce9698d59d77.png) 这一部分放入input.yaml的自定义节点库直接参与后面的clashcheck筛选？ 或者放入已筛选好的check.yaml直接参与后面的rm等后续流程？
> > > 我是问，前面pool产生的out.yaml move和rename 到这个文件夹不会覆盖？先执行手动放进去的input.yaml或者check.yaml?
> > 
> > 
> > 对于input.yaml你既可以手动添加也可以通过自动化流程自动把output.yaml转移到此文件夹的input.yaml 对于为什么在clashcheck文件夹下我有毛病的又加了两个次级文件夹是因为要为将来在容器挂载数据卷做准备
> 
> 我想明确的是，如果文件夹中有手动的input.yaml或者check.yaml，也有自动化的流程，最后的结果是执行自动化的还是先执行文件夹里这两个文件

这两个只是配置文件啊，具体情况根据配置文件里的内容执行的，如果配置文件里source写的是本地文件，就是引用本地文件，如果写的是远程文件就是用远程文件，没有先后之分，就算你在里面放了个input.yaml文件，配置文件如果写的是引用远程文件，就是引用远程文件

**Comment by yu-steven** [comment]
> > > > > 我没用本地环境，在github里整个过程运行也不管用
> > > > 
> > > > 
> > > > 哪里不管用
> > > 
> > > 
> > > 在github里用原nodes.yaml走全流程，rm/config.js里的自定义→ openitsub.com比如改成→ abc.com对上面提到的pool.yaml代码片段名字部分的无效，还是→ openitsub.com
> > 
> > 
> > 对上面的当然无效，因为pool.yaml是由根目录url触发的另一个自动化流程所产出的
> 
> url触发的那个管它的文件是哪个？

对于pool.yaml的产出触发的是根目录`url`文件

对于节点保留文件触发的是`sub/url2`

**Comment by anjue39** [comment]
如果默认设置，你不放input.yaml进去，自动化流程它也会从pool里拽过来产生一个input.yaml放进去，我问的重点是：自动产生的input.yaml会不会覆盖手动放进去的input.yaml



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月28日 17:30
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 这样的逻辑是错的，一个sleep的中间过程让一个事件一直不结束 (Issue #264)





    
 这一部分放入input.yaml的自定义节点库直接参与后面的clashcheck筛选？ 或者放入已筛选好的check.yaml直接参与后面的rm等后续流程？
 我是问，前面pool产生的out.yaml move和rename 到这个文件夹不会覆盖？先执行手动放进去的input.yaml或者check.yaml?
  
对于input.yaml你既可以手动添加也可以通过自动化流程自动把output.yaml转移到此文件夹的input.yaml 对于为什么在clashcheck文件夹下我有毛病的又加了两个次级文件夹是因为要为将来在容器挂载数据卷做准备
  
我想明确的是，如果文件夹中有手动的input.yaml或者check.yaml，也有自动化的流程，最后的结果是执行自动化的还是先执行文件夹里这两个文件
  
这两个只是配置文件啊，具体情况根据配置文件里的内容执行的，如果配置文件里source写的是本地文件，就是引用本地文件，如果写的是远程文件就是用远程文件，没有先后之分，就算你在里面放了个input.yaml文件，配置文件如果写的是引用远程文件，就是引用远程文件

**Comment by yu-steven** [comment]
> 如果默认设置，你不放input.yaml进去，自动化流程它也会从pool里拽过来产生一个input.yaml放进去，我问的重点是：自动产生的input.yaml会不会覆盖手动放进去的input.yaml 发自我的iPhone
> […](#)

虽然你的逻辑我听不懂，但是会的

**Comment by anjue39** [comment]
虽然你没听懂我的意思，但你看如果是覆盖的，就不能把本地生成的直接放进去。但实际上是不覆盖的，你上传本地的，就执行本地的。所以我问你



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年10月28日 19:02
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 这样的逻辑是错的，一个sleep的中间过程让一个事件一直不结束 (Issue #264)





  
如果默认设置，你不放input.yaml进去，自动化流程它也会从pool里拽过来产生一个input.yaml放进去，我问的重点是：自动产生的input.yaml会不会覆盖手动放进去的input.yaml 发自我的iPhone
 …
  
虽然你的逻辑我听不懂，但是会的

**Comment by yu-steven** [comment]
> 虽然你没听懂我的意思，但你看如果是覆盖的，就不能把本地生成的直接放进去。但实际上是不覆盖的，你上传本地的，就执行本地的。所以我问你 发自我的iPhone
> […](#)

你知道你还问我我听不懂的问题干啥

**Comment by yu-steven** [comment]
不懂就实践一下，就好了
