### ISSUE TITLE
Q: Fork之后 github Actions筛选出的节点全不可用

### ISSUE THREAD

**Issue by Mengzhiyaa** [yu-steven/openit#265]
### 详细说明

```bash
什么: 非常感谢你的项目，我有一个小需求就是想对一些其他的节点进行筛选。
我fork了你的项目，在没有改动代码的之前，使用同样的代码，仅对Node的workflow进行了修改（修改的方式参照你的注释）。但是我使用action筛选出来的节点大多数都是不可用的，而你筛选出来的节点大多数是可用的。我想问一下这其中的可能是哪里出现了问题。
```

### 这里有一些承诺需要审阅

- [X] 我会广泛传播这个项目
- [X] 这是我经过思考提出的问题
- [X] 我查阅了其他的issues，没有重复提问
- [X] 我承诺遵守社区指导方针

**Comment by yu-steven** [comment]
那是因为不用的GitHub国外服务器筛选当然是筛不出来节点；如果可以试着用国内服务器筛选，由GitHub Action拉取结果

对于更改筛选源请修改
https://github.com/yu-steven/openit/blob/main/utils/clashcheck/config/config.yaml
第四行
