### ISSUE TITLE
这个url.sh错误是哪的原因呢

### ISSUE THREAD

**Issue by anjue39** [yu-steven/openit#267]
![image](https://user-images.githubusercontent.com/98279987/199353094-9c1c4f63-1489-4d45-91bd-a36c2b851c83.png)

**Comment by anjue39** [comment]
https://github.com/yu-steven/openit/blob/bbb44e2580c10a13403c08080423942c535a2572/.github/workflows/Nodes.yaml#L53-L69

**Comment by yu-steven** [comment]
> https://github.com/yu-steven/openit/blob/bbb44e2580c10a13403c08080423942c535a2572/.github/workflows/Nodes.yaml#L53-L69
> 
> 
> 新增的这些secrect
> `${{ success() }} ${{ failure() && steps.clashcheck.conclusion == 'failure' }} `等，
> 影响fork后的运行吗

不影响

**Comment by anjue39** [comment]
以上收到👌🏻

**Comment by anjue39** [comment]
如何流程里添加用两个测速链接？
下载测速是最准的，目前实现起来成熟吗？

**Comment by anjue39** [comment]
> > ![image](https://user-images.githubusercontent.com/98279987/199353094-9c1c4f63-1489-4d45-91bd-a36c2b851c83.png)
> 
> 权限错误，你给url.sh一个+x的权限 `chmod +x url.sh`

本地加上了，push上去好像还是没权限。能在giugub上添加吗？为啥本地已经是10075了，传上去却有了权限？费解

**Comment by yu-steven** [comment]
> > > ![image](https://user-images.githubusercontent.com/98279987/199353094-9c1c4f63-1489-4d45-91bd-a36c2b851c83.png)
> > 
> > 
> > 权限错误，你给url.sh一个+x的权限 `chmod +x url.sh`
> 
> 本地加上了，push上去好像还是没权限。能在giugub上添加吗？为啥本地已经是10075了，传上去却有了权限？费解
> 
> 手动添加文件就有这个问题，git clone或者folk就没问题。费解

在GitHub上这样显示就可以用了
![34F6E3A5-C652-4A94-803F-D2D4E4668E91](https://user-images.githubusercontent.com/78414278/199400770-525ee78d-5cf8-4947-8a71-cb949e3e4aa0.jpeg)

**Comment by anjue39** [comment]
> > > > ![image](https://user-images.githubusercontent.com/98279987/199353094-9c1c4f63-1489-4d45-91bd-a36c2b851c83.png)
> > > 
> > > 
> > > 权限错误，你给url.sh一个+x的权限 `chmod +x url.sh`
> > 
> > 
> > 本地加上了，push上去好像还是没权限。能在giugub上添加吗？为啥本地已经是10075了，传上去却有了权限？费解
> > 手动添加文件就有这个问题，git clone或者folk就没问题。费解
> 
> 在GitHub上这样显示就可以用了 ![34F6E3A5-C652-4A94-803F-D2D4E4668E91](https://user-images.githubusercontent.com/78414278/199400770-525ee78d-5cf8-4947-8a71-cb949e3e4aa0.jpeg)

搞不定。查了资料，本地能搞定，传上去就不行。奇怪
git update-index --chmod=+x url.sh    ?
or
chmod +x url.sh  ?

**Comment by yu-steven** [comment]
第二种

**Comment by anjue39** [comment]
> chmod +x url.sh

不行，本地能加权限，传上去就不行

**Comment by yu-steven** [comment]
> > chmod +x url.sh
> 
> 不行，本地能加权限，传上去就不行

那就在Nodes.yaml的GitHub Action上加上 `chmod +x ./.github/url.sh`

**Comment by anjue39** [comment]
👌👌



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年11月2日 13:40
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 这个url.sh错误是哪的原因呢 (Issue #267)





   
chmod +x url.sh
  
不行，本地能加权限，传上去就不行
  
那就在Nodes.yaml的GitHub Action上加上 chmod +x ./.github/url.sh
