### ISSUE TITLE
程序筛选的有很多假快节点

### ISSUE THREAD

**Issue by anjue39** [yu-steven/openit#268]
![image](https://user-images.githubusercontent.com/98279987/200106869-8e31822c-5053-4c5d-a3d6-774ddd5f2547.png)

前面绿色延迟的其实都不能用，反而后面的延迟在400-1500能用，反而好用
代码测的入口机还是落地机的延迟？到入口机的延迟除了能去除连通无效节点外，其实没多大意义
反而在一些自动找url延迟低的软件中，假以乱真的被挑选上，结果又不能用

可以设置timeout的下限吗？也就是说可以设定一个范围吗，比如大于200，小于1500

**Comment by yu-steven** [comment]
你换一个测速源，建议使用我config.yaml模版上的测速源，或者最低要求也必须是https协议的，你不用强求你在GitHub的机器上能筛出什么好节点，即使你用的是http协议的测速源
https://github.com/yu-steven/openit/blob/90ddbf2068834a529198b779f418bbb8fdd8a46f/utils/clashcheck/config/config.yaml#L6

**Comment by anjue39** [comment]
我就是用的默认config的y2b那个测速链接，本地筛选的。你说的测速源是y2b那个还是测延迟的那个？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年11月5日 15:58
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 程序筛选的有很多假快节点 (Issue #268)





 
你换一个测速源，建议使用我config.yaml模版上的测速源，或者最低要求也必须是https协议的，你不用强求你在GitHub的机器上能筛出什么好节点，即使你用的是http协议的测速源
 https://github.com/yu-steven/openit/blob/90ddbf2068834a529198b779f418bbb8fdd8a46f/utils/clashcheck/config/config.yaml#L6

**Comment by yu-steven** [comment]
> 我就是用的默认config的y2b那个测速链接，本地筛选的。你说的测速源是y2b那个还是测延迟的那个？ 发自我的iPhone
> […](#)

啊对，y2b没错，那你机器是在哪测的，本地吗

**Comment by anjue39** [comment]
本地测的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年11月5日 16:05
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 程序筛选的有很多假快节点 (Issue #268)





  
我就是用的默认config的y2b那个测速链接，本地筛选的。你说的测速源是y2b那个还是测延迟的那个？ 发自我的iPhone
 …
  
啊对，y2b没错，那你机器是在哪测的，本地吗

**Comment by yu-steven** [comment]
> 本地测的 发自我的iPhone
> […](#)

那就很奇怪了，因为openit也是本地测的，为啥都好用捏

**Comment by anjue39** [comment]
当你本地把配置timeout由5000调到600-900时，就会出现。你可以试试。表现最快的绿色延迟的节点往往是假的，160ms以内的。


追问一下：代码测的是入口机还是落地机的延迟？我看了很多资料，本地-中转机-落地机，如果是测的全程的，也就是有中转机到落地机这第二段的，才会是更准确的。一些软件的可用性测试就是测的本地到落地机的延迟，更能反映可用性



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年11月5日 18:26
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 程序筛选的有很多假快节点 (Issue #268)





  
本地测的 发自我的iPhone
 …
  
那就很奇怪了，因为openit也是本地测的，为啥都好用捏

**Comment by anjue39** [comment]
另外，代码多处也用到这样的测速地址，http://www.gstatic.com/generate_204
，跟这个有关系吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Steven Yu ***@***.***&gt;
发送时间: 2022年11月5日 18:26
收件人: yu-steven/openit ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yu-steven/openit] 程序筛选的有很多假快节点 (Issue #268)





  
本地测的 发自我的iPhone
 …
  
那就很奇怪了，因为openit也是本地测的，为啥都好用捏

**Comment by yu-steven** [comment]
> 当你本地把配置timeout由5000调到600-900时，就会出现。你可以试试。表现最快的绿色延迟的节点往往是假的，160ms以内的。 追问一下：代码测的是入口机还是落地机的延迟？我看了很多资料，本地-中转机-落地机，如果是测的全程的，也就是有中转机到落地机这第二段的，才会是更准确的。一些软件的可用性测试就是测的本地到落地机的延迟，更能反映可用性 发自我的iPhone
> […](#)

那就改回5000ms啦，clashcheck之所以叫clashcheck是因为它用的clash内核，clash内核是测的RTT的一个来回，延迟肯定很大，所以需要给延迟大一些，然后clashcheck设计之初就是因为clash测两个RTT的延迟长度，所以准确，但是调小延迟这个我还真没试过

**Comment by yu-steven** [comment]
> 另外，代码多处也用到这样的测速地址，http://www.gstatic.com/generate_204 ，跟这个有关系吗 发自我的iPhone
> […](#)

哪里代码有这个？指定一下文件路径和行数

**Comment by yu-steven** [comment]
> 当你本地把配置timeout由5000调到600-900时，就会出现。你可以试试。表现最快的绿色延迟的节点往往是假的，160ms以内的。 追问一下：代码测的是入口机还是落地机的延迟？我看了很多资料，本地-中转机-落地机，如果是测的全程的，也就是有中转机到落地机这第二段的，才会是更准确的。一些软件的可用性测试就是测的本地到落地机的延迟，更能反映可用性 发自我的iPhone
> […](#)

我没说明白😂
两个RTT长度就是你说的本地-中转机-落地机然后再回来，所以叫两个RTT长度

**Comment by anjue39** [comment]
![image](https://user-images.githubusercontent.com/98279987/200116064-4b7959f7-0bcd-4afd-8dbd-480d15d2af48.png)
比如这四个，在openclash里同样也看延迟是不错的，但是这四个其实一个不能用，可能就是你说的估计没来得及测试一个来回就结束，也可能是因为他们这些软件的测速url的原因，如下图
![image](https://user-images.githubusercontent.com/98279987/200116162-f055b0b7-a6a7-4e36-b09a-a2e1dea524c1.png)

至于你说的这个测速url，在rule里多处出现，例举
![image](https://user-images.githubusercontent.com/98279987/200116282-70479467-5513-4c4a-8c1c-12c008952dd6.png)

**Comment by yu-steven** [comment]
> ![image](https://user-images.githubusercontent.com/98279987/200116064-4b7959f7-0bcd-4afd-8dbd-480d15d2af48.png) 比如这四个，在openclash里同样也看延迟是不错的，但是这四个其实一个不能用，可能就是你说的估计没来得及测试一个来回就结束，也可能是因为他们这些软件的测速url的原因，如下图 ![image](https://user-images.githubusercontent.com/98279987/200116162-f055b0b7-a6a7-4e36-b09a-a2e1dea524c1.png)
> 
> 至于你说的这个测速url，在rule里多处出现，例举 ![image](https://user-images.githubusercontent.com/98279987/200116282-70479467-5513-4c4a-8c1c-12c008952dd6.png)

列举的这些测速url跟clashcheck的代码毫无关系，clashcheck所有python代码都只存在于./utils/clashcheck

**Comment by yu-steven** [comment]
你说的延迟太低没来得及测试我觉得是这个原因

**Comment by anjue39** [comment]
![image](https://user-images.githubusercontent.com/98279987/200128507-9360fe4f-2383-4fc2-b3e7-bf4433125a6a.png)
这是本地timeout 4000筛选出来的，红色框内的都数值挺好，但都不能用，说明不是跟没来得及测试有关系。多发生在cn节点
你可能没有注意到这个现象

**Comment by anjue39** [comment]
![image](https://user-images.githubusercontent.com/98279987/200129348-b97d2502-1536-465e-b487-7ed7a19fe437.png)
这是cn 13457这个节点，如上图，数值表现很漂亮，但是不能用，我提供节点供你测试，你看看你能用吗，是不是也是测速延迟很好?
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIvCfh6jwn4ezQ04gNCDihpIgYW5qdWUiLA0KICAiYWRkIjogIjQ3Ljk0Ljg1LjIwOSIsDQogICJwb3J0IjogIjQ0MzMiLA0KICAiaWQiOiAiNzdhMjg2ZjQtMGEwYi00ZWY3LWFhZWYtYTRmZmY2MDg3MmU5IiwNCiAgImFpZCI6ICIwIiwNCiAgInNjeSI6ICJhdXRvIiwNCiAgIm5ldCI6ICJ0Y3AiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiNDcuOTQuODUuMjA5IiwNCiAgInBhdGgiOiAiLyIsDQogICJ0bHMiOiAiIiwNCiAgInNuaSI6ICIiDQp9
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIvCfh6jwn4ezQ04gNyDihpIgYW5qdWUiLA0KICAiYWRkIjogIjEyMC41NS42My44MyIsDQogICJwb3J0IjogIjQ0MzMiLA0KICAiaWQiOiAiNzdhMjg2ZjQtMGEwYi00ZWY3LWFhZWYtYTRmZmY2MDg3MmU5IiwNCiAgImFpZCI6ICIwIiwNCiAgInNjeSI6ICJhdXRvIiwNCiAgIm5ldCI6ICJ0Y3AiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiMTIwLjU1LjYzLjgzIiwNCiAgInBhdGgiOiAiLyIsDQogICJ0bHMiOiAiIiwNCiAgInNuaSI6ICIiDQp9
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIvCfh6jwn4ezQ04gMSDihpIgYW5qdWUiLA0KICAiYWRkIjogInMyLm1pbmUuY29tLmNuIiwNCiAgInBvcnQiOiAiNDQzMyIsDQogICJpZCI6ICI3N2EyODZmNC0wYTBiLTRlZjctYWFlZi1hNGZmZjYwODcyZTkiLA0KICAiYWlkIjogIjAiLA0KICAic2N5IjogImF1dG8iLA0KICAibmV0IjogInRjcCIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICJzMi5taW5lLmNvbS5jbiIsDQogICJwYXRoIjogIi8iLA0KICAidGxzIjogIiIsDQogICJzbmkiOiAiIg0KfQ==
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIvCfh6jwn4ezQ04gOSDihpIgYW5qdWUiLA0KICAiYWRkIjogIjEyMC41NS42My44MyIsDQogICJwb3J0IjogIjQ0MzMiLA0KICAiaWQiOiAiNzdhMjg2ZjQtMGEwYi00ZWY3LWFhZWYtYTRmZmY2MDg3MmU5IiwNCiAgImFpZCI6ICIwIiwNCiAgInNjeSI6ICJhdXRvIiwNCiAgIm5ldCI6ICJ0Y3AiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAibGcxLmNmY2RuMy54eXoiLA0KICAicGF0aCI6ICIvZG9uZ3RhaXdhbmcuY29tIiwNCiAgInRscyI6ICIiLA0KICAic25pIjogIiINCn0=
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIvCfh6jwn4ezQ04gNSDihpIgYW5qdWUiLA0KICAiYWRkIjogIjQ3Ljk0Ljg1LjIwOSIsDQogICJwb3J0IjogIjQ0MzMiLA0KICAiaWQiOiAiNzdhMjg2ZjQtMGEwYi00ZWY3LWFhZWYtYTRmZmY2MDg3MmU5IiwNCiAgImFpZCI6ICIwIiwNCiAgInNjeSI6ICJhdXRvIiwNCiAgIm5ldCI6ICJ0Y3AiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAibGcxLmNmY2RuMy54eXoiLA0KICAicGF0aCI6ICIvZG9uZ3RhaXdhbmcuY29tIiwNCiAgInRscyI6ICIiLA0KICAic25pIjogIiINCn0=

**Comment by anjue39** [comment]
![image](https://user-images.githubusercontent.com/98279987/200129730-5d4b7d0b-5f89-4884-9c69-aa11790e875d.png)
参照另一个issures #98

**Comment by anjue39** [comment]
如果换成 `http://www.google.com/generate_204`
那么就会没有绿色的节点
![image](https://user-images.githubusercontent.com/98279987/200130282-d854b730-7c39-42c5-b445-85581da83c26.png)

结合出现的情况多cn节点以及我反应的问题，
综合clashcheck中我觉得也可能是这样的问题，也是用了gstatic的延迟测速链接，不准确。你说跟这个测速链接没关系，其实是有有关系的

**Comment by anjue39** [comment]
![image](https://user-images.githubusercontent.com/98279987/200130919-30638fb1-43dd-46e8-9413-d5f99c8fc384.png)
pool中用到了这个测速链接，所以clashcheck之前引入过来的节点库就潜伏着这样的问题。clashcheck中的测速链接y2b我觉得麻木这样的问题，导致最后订阅后的结果也有感染。不要总说你那没问题呀，你是没有遇见或者没有注意到。有问题多观察和测试，也许我说的是问题呢

**Comment by anjue39** [comment]
![Uploading image.png…]()
代码中出现多处url测速链接不统一的情况，https和http也使用的标准不统一
默认的数值搞清到底是https还是http链接对应的？看别人反应延迟能差3倍，到底哪种更匹配合理

**Comment by anjue39** [comment]
![Uploading image.png…]()
代码中出现多处url测速链接不统一的情况，https和http也使用的标准不统一
默认的数值搞清到底是https还是http链接对应的？看别人反应延迟能差3倍，到底哪种更匹配合理

**Comment by yu-steven** [comment]
> ![image](https://user-images.githubusercontent.com/98279987/200129730-5d4b7d0b-5f89-4884-9c69-aa11790e875d.png)
> 参照另一个issures
> [Kr328/ClashForAndroid#98](https://github.com/Kr328/ClashForAndroid/issues/98)

我上面跟你说过了，gstatic那些不参与代码使用，能不能思考一下

**Comment by yu-steven** [comment]
> 如果换成 `http://www.google.com/generate_204` 那么就会没有绿色的节点 ![image](https://user-images.githubusercontent.com/98279987/200130282-d854b730-7c39-42c5-b445-85581da83c26.png)
> 
> 结合出现的情况多cn节点以及我反应的问题， 综合clashcheck中我觉得也可能是这样的问题，也是用了gstatic的延迟测速链接，不准确。你说跟这个测速链接没关系，其实是有有关系的

clashcheck用的是google筛的，你这个唯一可能的问题是你本地筛选的时候是挂着代理

**Comment by yu-steven** [comment]
> ![image](https://user-images.githubusercontent.com/98279987/200130919-30638fb1-43dd-46e8-9413-d5f99c8fc384.png) pool中用到了这个测速链接，所以clashcheck之前引入过来的节点库就潜伏着这样的问题。clashcheck中的测速链接y2b我觉得麻木这样的问题，导致最后订阅后的结果也有感染。不要总说你那没问题呀，你是没有遇见或者没有注意到。有问题多观察和测试，也许我说的是问题呢
> 
> 你拿我给你的节点试，放心能过审，但是不能用。不知道你拿到的时候节点还有没有。
> 
> 另外需要探讨一个问题，是用https还是用http，有人也反映过类似的问题 ![image](https://user-images.githubusercontent.com/98279987/200131379-d4209208-902b-43dd-9d2b-5eb7c740d4ba.png)

http是不准确的，https测试可以更准确，之前的issues里给你讲了https更准，我看你也没问我问题，就是在那感觉，如果你不是来问我问题的，那你开issue干啥

**Comment by yu-steven** [comment]
> ![image](https://user-images.githubusercontent.com/98279987/200132014-f6b367a7-7526-46ee-ac4c-4dd83a51736f.png)
> 
> 代码中出现多处url测速链接不统一的情况，https和http也使用的标准不统一 默认的数值搞清到底是https还是http链接对应的？看别人反应延迟能差3倍，我虽然实测没那么多倍，但确实数值差不少，到底哪种更匹配合理，因为代码中有默认对应的数值，是否合理？

你能不能好好把整个系统了解完全后再跟我讲你的怀疑，我现在挨个给你说哈
clash.yaml理的测试是测试可用性，然而抱歉那是google.com不存在假节点，除非你自己改了
quanx.conf里的那两个地址是用于测试网络连通性的，不是筛选用的
pool.yaml跟你说了，就tm跟那没关系
all_base.tpl里的这个是quanx配置文件的，完全不沾边
最后两个是subconverter默认配置文件，根本用不到

**Comment by yu-steven** [comment]
最后，请在提issues的时候一口气写完，而不是把issues当即时通讯软件😅

**Comment by anjue39** [comment]
1.我已找到问题原因，非本地有代理测速，我也知道clashcheck跟那个测延迟的没关系，你实际测了我给你的那几个节点了你肯定没测，我反应的情况属实，也跟每个人用的翻墙软件测延迟的测速地址不当有关系。你说的也没错，可能测延迟时间不够，但也不全是这方面的原因，有的不显示延迟的或者数值大的也照样可以用，我不质疑你，也别质疑我对你系统了解的程度。
2.另我给你提供那些测速地址，是想告诉你，如果整套代码文件里涉及测速按https，就全部按https，有的是https，有的是http，还有的比如http://www.gstatic.com/generate_204，有的是https，有的是http，按你说的就应该都是https://www.gstatic.com/generate_204，虽然很多都在rule规则里。我给你反映的问题就是因为本地翻墙软件设置延迟地址不当造成的那些错误的显示，一并分享给你，让你也统一一下这些地址。我知道跟clashcheck没关系，就是建议。你总觉得我在说跟主题无关的，确实，我说的就是跟主题无关的建议，但是由这个主题解决方法提醒到的点。
3.除了你说的可能测速时间不够外，还有一个原因就是测速文件太小，测联通的文件也太小，虽然大部分时候是正常的
4.issues成了论坛也非我本意，问题不是一下子产生的，我尽量不说话了，但没有我，你会很孤单，孤勇者。

无论如何，最后感谢你的答复

**Comment by yu-steven** [comment]
> 1.我已找到问题原因，非本地有代理测速，我也知道clashcheck跟那个测延迟的没关系，我给你的那几个节点了你肯定没测，我反应的情况属实，也跟每个人用的翻墙软件测延迟的测速地址不当有关系。你说的也没错，可能测延迟时间不够，但也不全是这方面的原因，有的不显示延迟的或者数值大的也照样可以用，我不质疑你，也别质疑我对你系统了解的程度。 2.另我给你提供那些测速地址，是想告诉你，如果整套代码文件里涉及测速按https，就全部按https，有的是https，有的是http，还有的比如[http://www.gstatic.com/generate_204，有的是https，有的是http，按你说的就应该都是https://www.gstatic.com/generate_204，虽然很多都在rule规则里。我给你反映的问题就是因为本地翻墙软件设置延迟地址不当造成的那些错误的显示，一并分享给你，让你也统一一下这些地址。我知道跟clashcheck没关系，就是建议。你总觉得我在说跟主题无关的，确实，我说的就是跟主题无关的建议，但是由这个主题解决方法提醒到的点。](http://www.gstatic.com/generate_204%EF%BC%8C%E6%9C%89%E7%9A%84%E6%98%AFhttps%EF%BC%8C%E6%9C%89%E7%9A%84%E6%98%AFhttp%EF%BC%8C%E6%8C%89%E4%BD%A0%E8%AF%B4%E7%9A%84%E5%B0%B1%E5%BA%94%E8%AF%A5%E9%83%BD%E6%98%AFhttps://www.gstatic.com/generate_204%EF%BC%8C%E8%99%BD%E7%84%B6%E5%BE%88%E5%A4%9A%E9%83%BD%E5%9C%A8rule%E8%A7%84%E5%88%99%E9%87%8C%E3%80%82%E6%88%91%E7%BB%99%E4%BD%A0%E5%8F%8D%E6%98%A0%E7%9A%84%E9%97%AE%E9%A2%98%E5%B0%B1%E6%98%AF%E5%9B%A0%E4%B8%BA%E6%9C%AC%E5%9C%B0%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6%E8%AE%BE%E7%BD%AE%E5%BB%B6%E8%BF%9F%E5%9C%B0%E5%9D%80%E4%B8%8D%E5%BD%93%E9%80%A0%E6%88%90%E7%9A%84%E9%82%A3%E4%BA%9B%E9%94%99%E8%AF%AF%E7%9A%84%E6%98%BE%E7%A4%BA%EF%BC%8C%E4%B8%80%E5%B9%B6%E5%88%86%E4%BA%AB%E7%BB%99%E4%BD%A0%EF%BC%8C%E8%AE%A9%E4%BD%A0%E4%B9%9F%E7%BB%9F%E4%B8%80%E4%B8%80%E4%B8%8B%E8%BF%99%E4%BA%9B%E5%9C%B0%E5%9D%80%E3%80%82%E6%88%91%E7%9F%A5%E9%81%93%E8%B7%9Fclashcheck%E6%B2%A1%E5%85%B3%E7%B3%BB%EF%BC%8C%E5%B0%B1%E6%98%AF%E5%BB%BA%E8%AE%AE%E3%80%82%E4%BD%A0%E6%80%BB%E8%A7%89%E5%BE%97%E6%88%91%E5%9C%A8%E8%AF%B4%E8%B7%9F%E4%B8%BB%E9%A2%98%E6%97%A0%E5%85%B3%E7%9A%84%EF%BC%8C%E7%A1%AE%E5%AE%9E%EF%BC%8C%E6%88%91%E8%AF%B4%E7%9A%84%E5%B0%B1%E6%98%AF%E8%B7%9F%E4%B8%BB%E9%A2%98%E6%97%A0%E5%85%B3%E7%9A%84%E5%BB%BA%E8%AE%AE%EF%BC%8C%E4%BD%86%E6%98%AF%E7%94%B1%E8%BF%99%E4%B8%AA%E4%B8%BB%E9%A2%98%E8%A7%A3%E5%86%B3%E6%96%B9%E6%B3%95%E6%8F%90%E9%86%92%E5%88%B0%E7%9A%84%E7%82%B9%E3%80%82) 3.除了你说的可能测速时间不够外，还有一个原因就是测速文件太小，测联通的文件也太小，虽然大部分时候是正常的 4.issues成了论坛也非我本意，问题不是一下子产生的，我尽量不说话了，但没有我这样关注和参与讨论的，你会很孤单，孤勇者。 5.难道我反馈的有时候不准的原因说的不中肯吗？
> 
> 无论如何，最后感谢你的答复

感谢理解，你的问题我明白了，能解决我也非常高兴🙏

**Comment by anjue39** [comment]
事实上，我在本地根据我的感觉和我给你的建议调整了，现在不仅测速准确，而且大部分都5-8m的y2b速度，且几乎都能用，不管延迟显示多少。

我去close

**Comment by yu-steven** [comment]
因为我总是孤独的，所以对于突然有人来提这么多问题我有应激反应，谢谢理解啦

**Comment by anjue39** [comment]
> 因为我总是孤独的，所以对于突然有人来提这么多问题我有应激反应，谢谢理解啦

一样的，我也很孤独，我也看不上很多人，很多人确实也不如自己。但不乏也有很多建议是可以get到的，自己看不到自己代码的问题，也不可能所有情况都会遇到。

**Comment by yu-steven** [comment]
OK👌

**Comment by anjue39** [comment]
1.gstatic里有大陆内的节点，如果节点通过gstatic可能会导致测速有速度，且不高或者很高，但是实际不能访问外网的问题。
2.本地翻墙软件测延迟的网址用的是http，不是https，也会造成与你的代码筛选出来的节点不符。
3.我手动设置的timeout过小，再加上代码默认的测速文件也不大，测连通的文件更不大，加起来造成筛选不精准，只有几个是真的能用。
-----以上就算是我自己翻墙软件设置的问题
但那些假绿色节点能筛选没被过滤遗漏过来，是我给你说的那些原因。相关测速文件的问题，因为测速文件过小造成的另一种来不及测试好造成的不精准。
