### ISSUE TITLE
更新订阅失败

### ISSUE THREAD

**Issue by wzkzs** [yu-steven/openit#269]
使用openit里的节点无法更新订阅
![Screenshot_2022-11-06-13-06-07-111_com.github.kr328.clash.jpg](https://user-images.githubusercontent.com/57616924/200155233-7b868b14-def4-4fd8-b0e0-0d0990e5f67f.jpg)

**Comment by yu-steven** [comment]
证书过期或系统时间不正确

**Comment by yu-steven** [comment]
证书过期或系统时间不准确

**Comment by wzkzs** [comment]
把例外网站改了就可以更新订阅了。
原来是全球直连，
现在是节点选择。
我觉得是没把openit订阅的网站加入代理列表吧
![Screenshot_2022-11-07-09-56-30-283_com.github.kr328.clash.jpg](https://user-images.githubusercontent.com/57616924/200211286-c27c6f91-bf20-4cac-92d1-aa2a50a9b5e2.jpg)

**Comment by yu-steven** [comment]
或许是这个原因，那你觉得我需要把默认设置改了吗

**Comment by wzkzs** [comment]
> 或许是这个原因，那你觉得我需要把默认设置改了吗

可以把更新订阅的域名加到代理列表进去，这样可以保证更新订阅能成功，其他的规则都不受影响。

**Comment by yu-steven** [comment]
> > 或许是这个原因，那你觉得我需要把默认设置改了吗
> 
> 可以把更新订阅的域名加到代理列表进去，这样可以保证更新订阅能成功，其他的规则都不受影响。

也可，我参考一下

**Comment by anjue39** [comment]
> > 或许是这个原因，那你觉得我需要把默认设置改了吗
> 
> 可以把更新订阅的域名加到代理列表进去，这样可以保证更新订阅能成功，其他的规则都不受影响。

如何加入到代理列表
