### ISSUE TITLE
测的是本地到落地机还是中转到落地机的延迟？

### ISSUE THREAD

**Issue by anjue39** [yu-steven/openit#280]
https://github.com/yu-steven/openit/blob/2b10a59c8163b917df92491496051defd13f6463/utils/clashcheck/config/config.yaml#L6

1.这测的是本地到落地机还是中转到落地机的延迟？
2.如果是本地clashcheck，都是本地环境非翻墙环境下筛选的，一个外链的y2b地址不可能连通呀？所以问第1个问题
3.此处测速地址的js文件大小跟精准度关系大不大？
4.备注说明必须是GFW完全屏蔽的网站，不明白啥意思。如果被屏蔽，无论如何本地也连不通测速地址呀，所以问第1个问题，如果可以翻墙，那测的不算是本地到落地机测速地址真实的延迟，矛盾

**Comment by yu-steven** [comment]
> https://github.com/yu-steven/openit/blob/2b10a59c8163b917df92491496051defd13f6463/utils/clashcheck/config/config.yaml#L6
> 
> 1.这测的是本地到落地机还是中转到落地机的延迟？ 2.如果是本地clashcheck，都是本地环境非翻墙环境下筛选的，一个外链的y2b地址不可能连通呀？所以问第1个问题 3.此处测速地址的js文件大小跟精准度关系大不大？ 4.备注说明必须是GFW完全屏蔽的网站，不明白啥意思。如果被屏蔽，无论如何本地也连不通测速地址呀，所以问第1个问题，如果可以翻墙，那测的不算是本地到落地机测速地址真实的延迟，矛盾

这东西原理跟你在v2ray用google测试节点延迟一个意思，再不懂我再跟你细讲

**Comment by anjue39** [comment]
> > https://github.com/yu-steven/openit/blob/2b10a59c8163b917df92491496051defd13f6463/utils/clashcheck/config/config.yaml#L6
> > 
> > 1.这测的是本地到落地机还是中转到落地机的延迟？ 2.如果是本地clashcheck，都是本地环境非翻墙环境下筛选的，一个外链的y2b地址不可能连通呀？所以问第1个问题 3.此处测速地址的js文件大小跟精准度关系大不大？ 4.备注说明必须是GFW完全屏蔽的网站，不明白啥意思。如果被屏蔽，无论如何本地也连不通测速地址呀，所以问第1个问题，如果可以翻墙，那测的不算是本地到落地机测速地址真实的延迟，矛盾
> 
> 这东西原理跟你在v2ray用google测试节点延迟一个意思，再不懂我再跟你细讲

谢谢，其实你只需简单直接回复我以上四个问题即可，比如第1.，我只需你明确回复测的哪一程，比如第3，我只需明确你的答复是关系大不大即可，第2、4我不明白

**Comment by yu-steven** [comment]
> > > https://github.com/yu-steven/openit/blob/2b10a59c8163b917df92491496051defd13f6463/utils/clashcheck/config/config.yaml#L6
> > > 
> > > 1.这测的是本地到落地机还是中转到落地机的延迟？ 2.如果是本地clashcheck，都是本地环境非翻墙环境下筛选的，一个外链的y2b地址不可能连通呀？所以问第1个问题 3.此处测速地址的js文件大小跟精准度关系大不大？ 4.备注说明必须是GFW完全屏蔽的网站，不明白啥意思。如果被屏蔽，无论如何本地也连不通测速地址呀，所以问第1个问题，如果可以翻墙，那测的不算是本地到落地机测速地址真实的延迟，矛盾
> > 
> > 
> > 这东西原理跟你在v2ray用google测试节点延迟一个意思，再不懂我再跟你细讲
> 
> 谢谢，其实你只需简单直接回复我以上四个问题即可，比如第1.，我只需你明确回复测的哪一程，比如第3，我只需明确你的答复是关系大不大即可，第2、4我不明白

但是你这四个问题是相互关联纠缠的，我只能概括的跟你说咯

**Comment by anjue39** [comment]
简单概括地说就行
