### ISSUE TITLE
求助：actions被提示已占用100%了怎么办

### ISSUE THREAD

**Issue by anjue39** [yu-steven/openit#281]
```
题外求助：actions被提示已占用100%了怎么办

```

**Comment by yu-steven** [comment]
什么样的占用100%？给个图

**Comment by anjue39** [comment]
正要close issure，看到你的回复。我已批量删除以前的workflows runs，不知道是不是。应该是触发了actions免费版的2000 commit的限制。你的也有这个问题。附图如下
![image](https://user-images.githubusercontent.com/98279987/202887371-e67668d0-0397-4f3f-80db-09b084ae9862.png)

**Comment by yu-steven** [comment]
我的没有这个问题，你这个是达到用量限制
openit的GitHub Action每天最少使用37次，最多使用57次，外加7-15次的节点入库push触发，然鹅从来没有出现此限制

**Comment by yu-steven** [comment]
> 正要close issure，看到你的回复。我已批量删除以前的workflows runs，不知道是不是。应该是触发了actions免费版的2000 commit的限制。你的也有这个问题。附图如下
> ![image](https://user-images.githubusercontent.com/98279987/202887371-e67668d0-0397-4f3f-80db-09b084ae9862.png)

你这个问题关键在于你设置存储库为私有存储库，如此必会达到每月上限

**Comment by anjue39** [comment]
两行代码里一个bug一个疑问❓
bug：(https://github.com/yu-steven/openit/blob/ab3ec58dbfaf80be3de2942275d9580ad4edc623/utils/pool/config.yaml#L64)
文件名后面应该是sub_merge_clash.yml，文件名已更换
疑问：https://github.com/yu-steven/openit/blob/ab3ec58dbfaf80be3de2942275d9580ad4edc623/utils/pool/config.yaml#L65
output.yaml为上次采集到的未筛选的全部节点，本次main.py再次采集入库上一次没啥必要，反而增加工作量，直接用上次筛选完的结果pool.yaml入库更科学

**Comment by anjue39** [comment]
> > 正要close issure，看到你的回复。我已批量删除以前的workflows runs，不知道是不是。应该是触发了actions免费版的2000 commit的限制。你的也有这个问题。附图如下
> > ![image](https://user-images.githubusercontent.com/98279987/202887371-e67668d0-0397-4f3f-80db-09b084ae9862.png)
> 
> 你这个问题关键在于你设置存储库为私有存储库，如此必会达到每月上限

我是publice的repo呀

**Comment by yu-steven** [comment]
> 两行代码里一个bug一个疑问❓ bug：(
> 
> https://github.com/yu-steven/openit/blob/ab3ec58dbfaf80be3de2942275d9580ad4edc623/utils/pool/config.yaml#L64
> 
> )
> 文件名后面应该是sub_merge_clash.yml，文件名已更换
> 疑问：
> https://github.com/yu-steven/openit/blob/ab3ec58dbfaf80be3de2942275d9580ad4edc623/utils/pool/config.yaml#L65
> 
> 
> output.yaml为上次采集到的未筛选的全部节点，本次main.py再次采集入库上一次没啥必要，反而增加工作量，直接用上次筛选完的结果pool.yaml入库更科学

你貌似还是没理解`pool.yaml`的意义，`pool.yaml`是用来转换并过渡入库来的节点，如果你非常喜欢用`pool.yaml`就创建一个`pool.yaml`然后把`output.yaml`改成`pool.yaml`

**Comment by yu-steven** [comment]
> > > 正要close issure，看到你的回复。我已批量删除以前的workflows runs，不知道是不是。应该是触发了actions免费版的2000 commit的限制。你的也有这个问题。附图如下
> > > ![image](https://user-images.githubusercontent.com/98279987/202887371-e67668d0-0397-4f3f-80db-09b084ae9862.png)
> > 
> > 
> > 你这个问题关键在于你设置存储库为私有存储库，如此必会达到每月上限
> 
> 我是publice的repo呀

no，我是说你账户里有某一个存储库设置为私有并且使用了action并且超出了限制

**Comment by anjue39** [comment]
> > 两行代码里一个bug一个疑问❓ bug：(
> > https://github.com/yu-steven/openit/blob/ab3ec58dbfaf80be3de2942275d9580ad4edc623/utils/pool/config.yaml#L64
> > 
> > )
> > 文件名后面应该是sub_merge_clash.yml，文件名已更换
> > 疑问：
> > https://github.com/yu-steven/openit/blob/ab3ec58dbfaf80be3de2942275d9580ad4edc623/utils/pool/config.yaml#L65
> > 
> > output.yaml为上次采集到的未筛选的全部节点，本次main.py再次采集入库上一次没啥必要，反而增加工作量，直接用上次筛选完的结果pool.yaml入库更科学
> 
> 你貌似还是没理解`pool.yaml`的意义，`pool.yaml`是用来转换并过渡入库来的节点，如果你非常喜欢用`pool.yaml`就创建一个`pool.yaml`然后把`output.yaml`改成`pool.yaml`

pool.yaml是上次url的节点，比如上次采集到2000个节点，筛选后最后生成100个 url。这个文件是把上次订阅的结果url转为标准格式，我记得是这样的，这是上次结果的转换后的clash文件
output.yaml是为筛选仅入库的节点，如上那根据config.yaml采集到的2000个节点库。最后转换后的clash文件，

如果我以上理解没问题，那么本地订阅直接用上次的订阅结果那100个入库重新筛选就行了，而不用把2000个节点再来一遍

**Comment by anjue39** [comment]
> > > > 正要close issure，看到你的回复。我已批量删除以前的workflows runs，不知道是不是。应该是触发了actions免费版的2000 commit的限制。你的也有这个问题。附图如下
> > > > ![image](https://user-images.githubusercontent.com/98279987/202887371-e67668d0-0397-4f3f-80db-09b084ae9862.png)
> > > 
> > > 
> > > 你这个问题关键在于你设置存储库为私有存储库，如此必会达到每月上限
> > 
> > 
> > 我是publice的repo呀
> 
> no，我是说你账户里有某一个存储库设置为私有并且使用了action并且超出了限制

这应该是有一个，我去看看

**Comment by yu-steven** [comment]
> > > 两行代码里一个bug一个疑问❓ bug：(
> > > https://github.com/yu-steven/openit/blob/ab3ec58dbfaf80be3de2942275d9580ad4edc623/utils/pool/config.yaml#L64
> > > 
> > > )
> > > 文件名后面应该是sub_merge_clash.yml，文件名已更换
> > > 疑问：
> > > https://github.com/yu-steven/openit/blob/ab3ec58dbfaf80be3de2942275d9580ad4edc623/utils/pool/config.yaml#L65
> > > 
> > > output.yaml为上次采集到的未筛选的全部节点，本次main.py再次采集入库上一次没啥必要，反而增加工作量，直接用上次筛选完的结果pool.yaml入库更科学
> > 
> > 
> > 你貌似还是没理解`pool.yaml`的意义，`pool.yaml`是用来转换并过渡入库来的节点，如果你非常喜欢用`pool.yaml`就创建一个`pool.yaml`然后把`output.yaml`改成`pool.yaml`
> 
> pool.yaml是上次url的节点，比如上次采集到2000个节点，筛选后最后生成100个 url。这个文件是把上次订阅的结果url转为标准格式，我记得是这样的，这是上次结果的转换后的clash文件 output.yaml是为筛选仅入库的节点，如上那根据config.yaml采集到的2000个节点库。最后转换后的clash文件，
> 
> 如果我以上理解没问题，那么本地订阅直接用上次的订阅结果那100个入库重新筛选就行了，而不用把2000个节点再来一遍

`pool.yaml`是怎么样定义的是我来定义的，它的意义有且只有一种意义，即节点入库，而之所以我去掉了`pool.yaml`是因为我节点从`url`入库到`output.yaml`的action我修改成直接入库，而不是经过`pool.yaml`，这样更加简单粗暴直接
如果你不想，你就不弄，你想，你就按照你想的方式去做，但是`pool.yaml`在之前就是入库之所用
