### ISSUE TITLE
Q: 有没有大佬可以说说OpenPCRS怎么可以docker运行吗..

### ISSUE THREAD

**Issue by lengshu** [yu-steven/openit#282]
### 详细说明

```bash
有台群晖 闲着也是闲着..
我这的网络环境有点恶略.
每次只用openit筛选好的订阅大概率要手动自己再测速再筛选.

如果可以docker运行的话,应该具体怎么操作?
目前个人水平只停留在可以按照教程安装个简单的docker项目  比如ql.测速之类的..
会不会很复杂
```

### 这里有一些承诺需要审阅

- [X] 我会广泛传播这个项目
- [X] 这是我经过思考提出的问题
- [X] 我查阅了其他的issues，没有重复提问
- [X] 我承诺遵守社区指导方针

**Comment by yu-steven** [comment]
用Docker运行在仓库的README里写了
https://github.com/yu-steven/openit#dockerfile
