### ISSUE TITLE
B: brave浏览器自动同步被规则拒绝了，请添加到支持访问的国外网站：

### ISSUE THREAD

**Issue by petercao** [yu-steven/openit#283]
### 出现问题的订阅链接

https://raw.githubusercontent.com/yu-steven/openit/main/Clash.yaml

### 你使用的是哪个应用程序？

Clash for Windows

### 复现方式

```bash
1.
2.
3.
...
	行  8630:  - DOMAIN-SUFFIX,google.com.sg,👉 国外网站
	行  8630:  - DOMAIN-SUFFIX,brave.com.sg,👉 国外网站
```

**Comment by yu-steven** [comment]
收到🫡

**Comment by yu-steven** [comment]
修改好了，请回复是否符合期望～
https://github.com/yu-steven/openit/commit/d37fddcee9068dbc2f743716d706282cb2a4b001

**Comment by petercao** [comment]
还是不行啊，我刚测试了一把brave还是给墙了，
还有目前发现facebook, twitter,谷歌也给墙了，
兄弟这一版改的有点问题：
brave的照着这个添加即可，我验证通过的
 - DOMAIN-SUFFIX,medium.com,�� 国外网站
 - DOMAIN-SUFFIX,brave.com,�� 国外网站




***@***.***
 
发件人： Steven Yu
发送时间： 2022-11-23 13:41
收件人： yu-steven/openit
抄送： Peter Cao; Author
主题： Re: [yu-steven/openit] B: brave浏览器自动同步被规则拒绝了，请添加到支持访问的国外网站： (Issue #283)
修改好了，请回复是否符合期望～
d37fddc

**Comment by yu-steven** [comment]
这是不要给他墙啊，哈哈哈哈哈哈哈哈哈哈哈

**Comment by yu-steven** [comment]
诶，不对啊，谷歌什么的不都必须要通过代理吗

**Comment by yu-steven** [comment]
国外网站走的都是代理，要么你就在国外网站那一栏选择走直连好了
