### ISSUE TITLE
[安全问题] 项目维护者yu-steven疑似被中国警方控制

### ISSUE THREAD

**Issue by AnnaSamWho** [yu-steven/openit#287]
在12-02左右，[yu-steven](https://github.com/yu-steven)疑似被中国警方控制，其Telegram账号有可疑登录。我们目前尚未得到他的回应。我们担心他可能已经被中国警方控制，并且他可能已经遭到了监控和取证。在此期间，我们建议大家保持谨慎，并避免使用yu-steven的项目或与他进行沟通。

**Comment by Sunovn** [comment]
有没有截图啊

**Comment by teamxiaoli** [comment]
![IMG_20221208_163953](https://user-images.githubusercontent.com/117327326/206399275-d169da5c-98f6-4888-ba83-6b616b380389.jpg)
yusteven之前的个人频道用户名目前已被其他人(应该是他朋友)使用 根据其消息 yusteven应该问题不大

**Comment by teamxiaoli** [comment]
![IMG_20221209_162409](https://user-images.githubusercontent.com/117327326/206657801-7c9e98ad-14c3-4c7c-8450-7c8c443021fa.jpg)
@yustevench 可以自行验证……
我:看不懂 保重

**Comment by Dd1ck** [comment]
祝平安

**Comment by WMK965** [comment]
现在openitsub.com也没了。祝平安。。。。

**Comment by hezhongfeng** [comment]
最新的一个commit，删了~祝好

**Comment by lostever** [comment]
本来我就好奇，这评论的人怎么那么少，然后回顾了一下我这几天曲折的科学上网之路，最近墙又双叒升高了，今天差点进不来github,大部分人普通人可能折腾一下不行就放弃了，除非硬性需要（但是硬性需要一般不都是自己买的梯子吗）。他们连外网都上不了，又怎么会了解作者的情况。听说最近人工智能舆情风控大赚特赚，电子禁言离我们越来越近了，来发个牢骚，不喜勿喷。且行且珍惜吧，祝好。

**Comment by 2195535283** [comment]
唉，还会有这么好的项目吗。最近发现不能更新订阅了，上来看看...令人唏嘘

**Comment by pandamelive** [comment]
希望不要有事
