### ISSUE TITLE
iOS系统未指出之代理软件

### ISSUE THREAD

**Issue by yu-steven** [yu-steven/openit#66]
未指出之ssr系代理软件可以配上
> 名称
> 付费/免费，收费多少(以美元计)
> 软件在App store链接
   发送至本Issues下🙏

**Comment by git-yusteven** [comment]
test

**Comment by yu-steven** [comment]
> iOS : Potatso Lite (free)

OK，看到了

**Comment by yu-steven** [comment]
> iOS : Potatso Lite (free)

之前本来是在README里的，但是由于软件太差（只支持ss）所以就删了
