### ISSUE TITLE
Windows系统未指出之代理软件

### ISSUE THREAD

**Issue by yu-steven** [yu-steven/openit#67]
未指出之代理软件可以配上

> 名称
>来源，GitHub等最好开源
> 附上软件URL

发送至本Issues下🙏

**Comment by zzcabc** [comment]
https://github.com/HMBSbige/ShadowsocksR-Windows

**Comment by yu-steven** [comment]
> https://github.com/HMBSbige/ShadowsocksR-Windows

Okok
