### ISSUE TITLE
Android系统未指出之代理软件

### ISSUE THREAD

**Issue by yu-steven** [yu-steven/openit#69]
安卓系统apk软件包或者Google商店下载链接并附上软件名称至本Issues下

**Comment by e5u** [comment]
https://play.google.com/store/apps/details?id=io.nekohasekai.sagernet&hl=zh&gl=US

**Comment by git-yusteven** [comment]
> https://play.google.com/store/apps/details?id=io.nekohasekai.sagernet&hl=zh&gl=US

已添加，谢谢🙏
